# Generated by Django 5.2.3 on 2025-08-20 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='llm_backend',
            field=models.CharField(choices=[('questionnaires.llms.MockEvaluator', 'Mock Evaluator'), ('questionnaires.llms.VulnerableChatGPTEvaluator', 'Vulnerable ChatGPTEvaluator'), ('questionnaires.llms.BetterChatGPTEvaluator', 'Better ChatGPTEvaluator'), ('questionnaires.llms.SanitizingChatGPTEvaluator', 'Sanitizing ChatGPTEvaluator')], default='questionnaires.llms.MockEvaluator', max_length=255),
        ),
    ]
