# Generated by Django 5.2.8 on 2026-01-05 11:04

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_alter_questionnaire_llm_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetextquestion',
            name='hint',
            field=common.fields.MarkdownField(blank=True, help_text='Markdown-formatted hint or additional context shown to the user below the question.', null=True),
        ),
        migrations.AddField(
            model_name='freetextquestion',
            name='reviewer_notes',
            field=common.fields.MarkdownField(blank=True, help_text='Markdown-formatted notes for reviewers. Not shown to users.', null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='hint',
            field=common.fields.MarkdownField(blank=True, help_text='Markdown-formatted hint or additional context shown to the user below the question.', null=True),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='reviewer_notes',
            field=common.fields.MarkdownField(blank=True, help_text='Markdown-formatted notes for reviewers. Not shown to users.', null=True),
        ),
        migrations.AddField(
            model_name='questionnaire',
            name='description',
            field=common.fields.MarkdownField(blank=True, help_text='Markdown-formatted description shown to users before they start the questionnaire.', null=True),
        ),
        migrations.AddField(
            model_name='questionnairesection',
            name='description',
            field=common.fields.MarkdownField(blank=True, help_text='Markdown-formatted description shown at the top of this section.', null=True),
        ),
        migrations.AlterField(
            model_name='freetextquestion',
            name='question',
            field=common.fields.MarkdownField(help_text='The question text. Supports markdown formatting.'),
        ),
        migrations.AlterField(
            model_name='multiplechoicequestion',
            name='question',
            field=common.fields.MarkdownField(help_text='The question text. Supports markdown formatting.'),
        ),
    ]
