# Generated by Django 5.2.8 on 2026-01-06 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_add_markdown_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='llm_backend',
            field=models.CharField(choices=[('questionnaires.llms.MockEvaluator', 'Mock Evaluator'), ('questionnaires.llms.VulnerableChatGPTEvaluator', 'Vulnerable ChatGPTEvaluator'), ('questionnaires.llms.IntermediateChatGPTEvaluator', 'Intermediate ChatGPTEvaluator'), ('questionnaires.llms.BetterChatGPTEvaluator', 'Better ChatGPTEvaluator'), ('questionnaires.llms.SanitizingChatGPTEvaluator', 'Sanitizing ChatGPTEvaluator'), ('questionnaires.llms.SentinelChatGPTEvaluator', 'Sentinel ChatGPTEvaluator')], default='questionnaires.llms.SanitizingChatGPTEvaluator', max_length=255),
        ),
    ]
