# Generated by Django 5.2.8 on 2026-01-09 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0006_alter_questionnaire_llm_backend'),
    ]

    operations = [
        migrations.AddField(
            model_name='freetextquestion',
            name='depends_on_option',
            field=models.ForeignKey(blank=True, help_text='Question is only shown if this option was selected.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_%(class)s_questions', to='questionnaires.multiplechoiceoption'),
        ),
        migrations.AddField(
            model_name='multiplechoicequestion',
            name='depends_on_option',
            field=models.ForeignKey(blank=True, help_text='Question is only shown if this option was selected.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_%(class)s_questions', to='questionnaires.multiplechoiceoption'),
        ),
        migrations.AddField(
            model_name='questionnairesection',
            name='depends_on_option',
            field=models.ForeignKey(blank=True, help_text='Section is only shown if this option was selected.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_sections', to='questionnaires.multiplechoiceoption'),
        ),
    ]
