# Generated by Django 5.2.8 on 2026-01-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0007_add_depends_on_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairesubmission',
            name='metadata',
            field=models.JSONField(blank=True, help_text='Optional metadata about the submission context (e.g., source event).', null=True),
        ),
    ]
