# Generated by Django 5.2.10 on 2026-01-16 15:31

import common.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import questionnaires.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0008_add_submission_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('positive_weight', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Points scored when answered correctly. Defaults to 0 for informational questions.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('question', common.fields.MarkdownField(help_text='The question text. Supports markdown formatting.')),
                ('hint', common.fields.MarkdownField(blank=True, help_text='Markdown-formatted hint or additional context shown to the user below the question.', null=True)),
                ('reviewer_notes', common.fields.MarkdownField(blank=True, help_text='Markdown-formatted notes for reviewers. Not shown to users.', null=True)),
                ('negative_weight', models.DecimalField(decimal_places=2, default=Decimal('0.0'), help_text='Points deducted when answered incorrectly.', max_digits=5, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)])),
                ('is_fatal', models.BooleanField(default=False, help_text='A fatal question will fail the questionnaire.')),
                ('is_mandatory', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0, help_text='The order the questions are displayed. Ignored if questionnaire.shuffle_questions is True.')),
                ('allowed_mime_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Allowed MIME types (e.g., 'image/jpeg', 'application/pdf'). Empty = allow all.", size=None)),
                ('max_file_size', models.PositiveIntegerField(default=5242880, help_text='Maximum file size in bytes per file.')),
                ('max_files', models.PositiveIntegerField(default=1, help_text='Maximum number of files allowed for this question.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('depends_on_option', models.ForeignKey(blank=True, help_text='Question is only shown if this option was selected.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent_%(class)s_questions', to='questionnaires.multiplechoiceoption')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='questionnaires.questionnaire')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_questions', to='questionnaires.questionnairesection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuestionnaireFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('file', models.FileField(max_length=255, upload_to=questionnaires.models.questionnaire_file_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('file_hash', models.CharField(db_index=True, help_text='SHA-256 hash of file content for deduplication.', max_length=64)),
                ('mime_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes.')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaire_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FileUploadAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_answers', to='questionnaires.questionnairesubmission')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaires.fileuploadquestion')),
                ('files', models.ManyToManyField(related_name='file_upload_answers', to='questionnaires.questionnairefile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='questionnairefile',
            constraint=models.UniqueConstraint(fields=('uploader', 'file_hash'), name='unique_questionnaire_file_per_user'),
        ),
        migrations.AddIndex(
            model_name='fileuploadanswer',
            index=models.Index(fields=['submission', 'question'], name='fua_user_question_idx'),
        ),
        migrations.AddConstraint(
            model_name='fileuploadanswer',
            constraint=models.UniqueConstraint(fields=('submission', 'question'), name='unique_user_fileupload_answer'),
        ),
    ]
