# Generated by Django 5.2.10 on 2026-01-16 19:40

import common.fields
import questionnaires.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0009_fileuploadquestion_questionnairefile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnairefile',
            name='file',
            field=common.fields.ProtectedFileField(max_length=255, upload_to=common.fields.ProtectedUploadTo(questionnaires.models.questionnaire_file_upload_path)),
        ),
    ]
