# Generated by Django 5.2.10 on 2026-01-18 11:14

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_protected_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnairefile',
            name='preview',
            field=common.fields.ProtectedImageField(blank=True, help_text='800x800 preview (generated for image files).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionnairefile',
            name='thumbnail',
            field=common.fields.ProtectedImageField(blank=True, help_text='150x150 thumbnail (generated for image files).', max_length=255, null=True),
        ),
    ]
