# Generated by Django 5.2.11 on 2026-02-16 12:13

from django.db import migrations, models

# Old evaluator import paths → new import paths
VALUE_MAPPING = {
    "questionnaires.llms.VulnerableChatGPTEvaluator": "questionnaires.llms.SanitizingLLMEvaluator",
    "questionnaires.llms.IntermediateChatGPTEvaluator": "questionnaires.llms.SanitizingLLMEvaluator",
    "questionnaires.llms.BetterChatGPTEvaluator": "questionnaires.llms.SanitizingLLMEvaluator",
    "questionnaires.llms.SanitizingChatGPTEvaluator": "questionnaires.llms.SanitizingLLMEvaluator",
    "questionnaires.llms.SentinelChatGPTEvaluator": "questionnaires.llms.SentinelLLMEvaluator",
}


def migrate_llm_backend_values(apps, schema_editor):
    """Migrate old ChatGPT-named evaluator paths to new LLM-named paths."""
    Questionnaire = apps.get_model("questionnaires", "Questionnaire")
    for old_value, new_value in VALUE_MAPPING.items():
        Questionnaire.objects.filter(llm_backend=old_value).update(llm_backend=new_value)


def reverse_llm_backend_values(apps, schema_editor):
    """Reverse: map new LLM-named paths back to old ChatGPT-named paths."""
    Questionnaire = apps.get_model("questionnaires", "Questionnaire")
    Questionnaire.objects.filter(llm_backend="questionnaires.llms.SanitizingLLMEvaluator").update(
        llm_backend="questionnaires.llms.SanitizingChatGPTEvaluator"
    )
    Questionnaire.objects.filter(llm_backend="questionnaires.llms.SentinelLLMEvaluator").update(
        llm_backend="questionnaires.llms.SentinelChatGPTEvaluator"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0011_questionnairefile_preview_and_more'),
    ]

    operations = [
        # First, update existing data to use the new import paths
        migrations.RunPython(migrate_llm_backend_values, reverse_llm_backend_values),
        # Then, update the field choices and default
        migrations.AlterField(
            model_name='questionnaire',
            name='llm_backend',
            field=models.CharField(
                choices=[
                    ('questionnaires.llms.MockEvaluator', 'Mock Evaluator'),
                    ('questionnaires.llms.SanitizingLLMEvaluator', 'Sanitizing LLM Evaluator'),
                    ('questionnaires.llms.SentinelLLMEvaluator', 'Sentinel LLM Evaluator'),
                ],
                default='questionnaires.llms.SanitizingLLMEvaluator',
                max_length=255,
            ),
        ),
    ]
