# Generated by Django 5.2.17 on 2026-09-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0012_alter_questionnaire_llm_backend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='can_retake_after',
            field=models.DurationField(blank=True, help_text='How long to wait to be able to retake. Empty means no cooldown (retake immediately) for admission questionnaires, but no retake at all (terminal failure) for membership questionnaires.', null=True),
        ),
    ]
