# Generated by Django 5.2.3 on 2025-11-11 12:06

import common.fields
import datetime
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0003_add_download_ip2location_periodic_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notification_type', models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_cancelled', 'Ticket Cancelled'), ('ticket_refunded', 'Ticket Refunded'), ('payment_confirmation', 'Payment Confirmation'), ('event_open', 'Event Open'), ('event_created', 'Event Created'), ('event_updated', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('event_reminder', 'Event Reminder'), ('rsvp_confirmation', 'Rsvp Confirmation'), ('rsvp_updated', 'Rsvp Updated'), ('rsvp_cancelled', 'Rsvp Cancelled'), ('potluck_item_created', 'Potluck Item Created'), ('potluck_item_updated', 'Potluck Item Updated'), ('potluck_item_claimed', 'Potluck Item Claimed'), ('potluck_item_unclaimed', 'Potluck Item Unclaimed'), ('questionnaire_submitted', 'Questionnaire Submitted'), ('questionnaire_evaluation_result', 'Questionnaire Evaluation Result'), ('invitation_received', 'Invitation Received'), ('invitation_claimed', 'Invitation Claimed'), ('invitation_revoked', 'Invitation Revoked'), ('membership_granted', 'Membership Granted'), ('membership_promoted', 'Membership Promoted'), ('membership_removed', 'Membership Removed'), ('membership_request_approved', 'Membership Request Approved'), ('membership_request_rejected', 'Membership Request Rejected'), ('org_announcement', 'Org Announcement'), ('malware_detected', 'Malware Detected')], db_index=True, help_text='Type of notification (StrEnum value)', max_length=50)),
                ('title', models.CharField(blank=True, default='', help_text='Rendered notification title', max_length=255)),
                ('body', common.fields.MarkdownField(blank=True, default='', help_text='Rendered notification body (markdown/HTML)')),
                ('context', models.JSONField(default=dict, help_text='Structured context data (validated TypedDict)')),
                ('attachments', models.JSONField(blank=True, default=dict, help_text='Attachment metadata: {filename: {content_base64: str, mimetype: str}}')),
                ('read_at', models.DateTimeField(blank=True, db_index=True, help_text='When user marked notification as read', null=True)),
                ('archived_at', models.DateTimeField(blank=True, help_text='When user archived notification', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('channel', models.CharField(choices=[('in_app', 'In App'), ('email', 'Email'), ('telegram', 'Telegram')], db_index=True, max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=20)),
                ('attempted_at', models.DateTimeField(blank=True, help_text='When delivery was first attempted', null=True)),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, help_text='When delivery succeeded', null=True)),
                ('error_message', models.TextField(blank=True, help_text='Error message if delivery failed')),
                ('retry_count', models.PositiveIntegerField(default=0, help_text='Number of retry attempts')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Channel-specific data (email_log_id, telegram_msg_id, etc.)')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Delivery',
                'verbose_name_plural': 'Notification Deliveries',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('silence_all_notifications', models.BooleanField(default=False, help_text='Master switch to disable all notifications')),
                ('enabled_channels', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text="List of enabled channels: ['in_app', 'email', 'telegram']", size=None)),
                ('digest_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('hourly', 'Hourly digest'), ('daily', 'Daily digest'), ('weekly', 'Weekly digest')], default='immediate', help_text='How often to batch notifications', max_length=20)),
                ('digest_send_time', models.TimeField(default=datetime.time(9, 0), help_text="Preferred time for daily/weekly digests (user's local time)")),
                ('notification_type_settings', models.JSONField(blank=True, default=dict, help_text='Per-type settings: {notification_type: {enabled: bool, channels: []}}')),
                ('event_reminders_enabled', models.BooleanField(default=True, help_text='Receive reminders 14, 7, 1 days before events')),
                ('show_me_on_attendee_list', models.CharField(choices=[('always', 'Always display'), ('never', 'Never display'), ('to_members', 'Visible to other organization members'), ('to_invitees', 'Visible to other invitees at the same event'), ('to_both', 'Visible to both')], default='never', help_text='Attendee list visibility preference', max_length=20)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'notification_type', 'created_at'], name='notificatio_user_id_ef3643_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_46ad24_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['status', 'created_at'], name='notificatio_status_1e9b53_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['channel', 'status'], name='notificatio_channel_edd073_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationdelivery',
            index=models.Index(fields=['notification', 'channel'], name='notificatio_notific_7707f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificationdelivery',
            constraint=models.UniqueConstraint(fields=('notification', 'channel'), name='unique_notification_channel'),
        ),
    ]
