# Generated by Django 5.2.3 on 2025-11-11 12:06

import typing as t

from django.db import migrations


def create_notification_preferences_for_existing_users(apps: t.Any, schema_editor: t.Any) -> None:
    """Create notification preferences for all existing users.

    This migration handles users that existed before the post_save signal was added.
    The signal automatically creates preferences for new users.

    Both guest and regular users get in-app + email channels enabled by default.
    Guest users get 15 notification types disabled (only event participation essentials remain enabled).
    """
    RevelUser = apps.get_model("accounts", "RevelUser")
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")

    # Notification types to disable for guest users (matches signals.py logic)
    guest_disabled_types = [
        "event_open",  # Can't browse events
        "event_created",  # Can't follow organizations
        "potluck_item_created",  # Typically not participating
        "potluck_item_updated",
        "potluck_item_claimed",
        "potluck_item_unclaimed",
        "questionnaire_submitted",  # For staff, not guests
        "invitation_claimed",  # For organizers, not guests
        "membership_granted",  # Can't be members
        "membership_promoted",
        "membership_removed",
        "membership_request_approved",
        "membership_request_rejected",
        "org_announcement",  # Not members
        "malware_detected",  # System/admin only
    ]

    # Get all users who don't have notification preferences
    users_without_prefs = RevelUser.objects.filter(notification_preferences__isnull=True)

    preferences_to_create = []
    for user in users_without_prefs:
        # Both guest and regular users get both channels enabled by default
        enabled_channels = ["in_app", "email"]

        # Guest users get 15 notification types disabled
        if user.guest:
            notification_type_settings = {notif_type: {"enabled": False} for notif_type in guest_disabled_types}
        else:
            notification_type_settings = {}

        preferences_to_create.append(
            NotificationPreference(
                user=user,
                enabled_channels=enabled_channels,
                notification_type_settings=notification_type_settings,
                digest_frequency="immediate",  # Default to immediate mode
                silence_all_notifications=False,
                event_reminders_enabled=True,
            )
        )

    # Bulk create for efficiency
    if preferences_to_create:
        NotificationPreference.objects.bulk_create(preferences_to_create)


def reverse_migration(apps: t.Any, schema_editor: t.Any) -> None:
    """Delete all notification preferences."""
    NotificationPreference = apps.get_model("notifications", "NotificationPreference")
    NotificationPreference.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        ("accounts", "0001_initial"),  # Ensure accounts app is migrated first
    ]

    operations = [
        migrations.RunPython(
            create_notification_preferences_for_existing_users,
            reverse_code=reverse_migration,
        ),
    ]
