# Generated by Django 5.2.3 on 2025-11-12 18:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_add_download_ip2location_periodic_task'),
        ('notifications', '0002_create_notification_preferences_for_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notificationpreference',
            index=models.Index(fields=['digest_frequency', 'digest_send_time'], name='notificatio_digest__2a6189_idx'),
        ),
    ]
