# Generated by Django 5.2.3 on 2025-11-12 18:25

from django.db import migrations


def create_notification_periodic_tasks(apps, schema_editor):
    """Create periodic tasks for notification system."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Task 1: Send notification digests - Every hour
    digest_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Send notification digests",
        defaults={
            "task": "notifications.tasks.send_notification_digests",
            "crontab": digest_schedule,
            "enabled": True,
        },
    )

    # Task 2: Cleanup old notifications - Daily at 2 AM
    cleanup_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="2",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Cleanup old notifications",
        defaults={
            "task": "notifications.tasks.cleanup_old_notifications",
            "crontab": cleanup_schedule,
            "enabled": True,
        },
    )

    # Task 3: Retry failed deliveries - Every 6 hours
    retry_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="*/6",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Retry failed deliveries",
        defaults={
            "task": "notifications.tasks.retry_failed_deliveries",
            "crontab": retry_schedule,
            "enabled": True,
        },
    )


def delete_notification_periodic_tasks(apps, schema_editor):
    """Remove periodic tasks for notification system."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    task_names = [
        "Send notification digests",
        "Cleanup old notifications",
        "Retry failed deliveries",
    ]

    for task_name in task_names:
        try:
            task = PeriodicTask.objects.get(name=task_name)
            task.delete()
        except PeriodicTask.DoesNotExist:
            pass  # Task already gone, nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0003_notificationpreference_notificatio_digest__2a6189_idx"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(create_notification_periodic_tasks, reverse_code=delete_notification_periodic_tasks),
    ]
