# Generated by Django 5.2.3 on 2025-11-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_add_notification_periodic_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='city',
        ),
    ]
