# Generated by Django 5.2.3 on 2025-11-13 19:42

import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_remove_notificationpreference_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type_settings',
            field=models.JSONField(blank=True, default=notifications.models.get_default_notification_type_settings, help_text='Per-type settings: {notification_type: {enabled: bool, channels: []}}'),
        ),
    ]
