# Generated by Django 5.2.3 on 2025-11-16 11:56

import django.contrib.postgres.fields
import notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notificationpreference_notification_type_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_cancelled', 'Ticket Cancelled'), ('ticket_refunded', 'Ticket Refunded'), ('payment_confirmation', 'Payment Confirmation'), ('event_open', 'Event Open'), ('event_updated', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('event_reminder', 'Event Reminder'), ('rsvp_confirmation', 'Rsvp Confirmation'), ('rsvp_updated', 'Rsvp Updated'), ('rsvp_cancelled', 'Rsvp Cancelled'), ('potluck_item_created', 'Potluck Item Created'), ('potluck_item_updated', 'Potluck Item Updated'), ('potluck_item_claimed', 'Potluck Item Claimed'), ('potluck_item_unclaimed', 'Potluck Item Unclaimed'), ('potluck_item_deleted', 'Potluck Item Deleted'), ('questionnaire_submitted', 'Questionnaire Submitted'), ('questionnaire_evaluation_result', 'Questionnaire Evaluation Result'), ('invitation_received', 'Invitation Received'), ('invitation_request_created', 'Invitation Request Created'), ('membership_granted', 'Membership Granted'), ('membership_promoted', 'Membership Promoted'), ('membership_removed', 'Membership Removed'), ('membership_request_created', 'Membership Request Created'), ('membership_request_approved', 'Membership Request Approved'), ('membership_request_rejected', 'Membership Request Rejected'), ('org_announcement', 'Org Announcement')], db_index=True, help_text='Type of notification (StrEnum value)', max_length=50),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='enabled_channels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=list, help_text='Default channels for notifications. Can be overridden per notification type.', size=None),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='notification_type_settings',
            field=models.JSONField(blank=True, default=notifications.models.get_default_notification_type_settings, help_text='Per-type overrides: {notification_type: {enabled: bool, channels: []}}. Channels specified here OVERRIDE enabled_channels for that type.'),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='silence_all_notifications',
            field=models.BooleanField(default=False, help_text='Master kill switch - disables ALL notifications including in-app'),
        ),
    ]
