# Generated by Django 5.2.3 on 2025-11-17 00:00

from django.db import migrations


def create_event_reminder_periodic_task(apps, schema_editor):
    """Create periodic task for event reminders."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Event reminders - Daily at 9 AM UTC
    # Run at 9 AM to send reminders for events happening in 14, 7, or 1 days
    reminder_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="9",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Send event reminders",
        defaults={
            "task": "notifications.tasks.send_event_reminders",
            "crontab": reminder_schedule,
            "enabled": True,
        },
    )


def delete_event_reminder_periodic_task(apps, schema_editor):
    """Remove periodic task for event reminders."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Send event reminders")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass  # Task already gone, nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0008_alter_notification_notification_type"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(create_event_reminder_periodic_task, reverse_code=delete_event_reminder_periodic_task),
    ]
