# Generated by Django 5.2.3 on 2025-11-17 11:27

import django.contrib.postgres.indexes
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_add_event_reminder_periodic_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', 'user'], name='notif_type_user_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=django.contrib.postgres.indexes.GinIndex(fields=['context'], name='notif_context_gin_idx', opclasses=['jsonb_path_ops']),
        ),
    ]
