# Generated by Django 5.2.3 on 2025-11-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_notification_notif_type_user_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('ticket_created', 'Ticket Created'), ('ticket_updated', 'Ticket Updated'), ('ticket_cancelled', 'Ticket Cancelled'), ('ticket_refunded', 'Ticket Refunded'), ('ticket_checked_in', 'Ticket Checked In'), ('payment_confirmation', 'Payment Confirmation'), ('event_open', 'Event Open'), ('event_updated', 'Event Updated'), ('event_cancelled', 'Event Cancelled'), ('event_reminder', 'Event Reminder'), ('rsvp_confirmation', 'Rsvp Confirmation'), ('rsvp_updated', 'Rsvp Updated'), ('rsvp_cancelled', 'Rsvp Cancelled'), ('potluck_item_created', 'Potluck Item Created'), ('potluck_item_updated', 'Potluck Item Updated'), ('potluck_item_claimed', 'Potluck Item Claimed'), ('potluck_item_unclaimed', 'Potluck Item Unclaimed'), ('potluck_item_deleted', 'Potluck Item Deleted'), ('questionnaire_submitted', 'Questionnaire Submitted'), ('questionnaire_evaluation_result', 'Questionnaire Evaluation Result'), ('invitation_received', 'Invitation Received'), ('invitation_request_created', 'Invitation Request Created'), ('membership_granted', 'Membership Granted'), ('membership_promoted', 'Membership Promoted'), ('membership_removed', 'Membership Removed'), ('membership_request_created', 'Membership Request Created'), ('membership_request_approved', 'Membership Request Approved'), ('membership_request_rejected', 'Membership Request Rejected'), ('org_announcement', 'Org Announcement'), ('waitlist_spot_available', 'Waitlist Spot Available')], db_index=True, help_text='Type of notification (StrEnum value)', max_length=50),
        ),
    ]
