# Generated by Django 5.2.8 on 2025-11-25 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0011_alter_notification_notification_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationpreference',
            name='show_me_on_attendee_list',
        ),
    ]
