# Generated by Django 5.2.17 on 2026-09-29 23:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0122_ticket_tier_check_in_offsets'),
        ('notifications', '0026_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='muted_organizations',
            field=models.ManyToManyField(blank=True, help_text='Organizations whose announcements this user does not want to receive.', related_name='+', to='events.organization'),
        ),
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(help_text='Normalized via normalize_email_for_matching().', max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('complaint', 'Spam complaint'), ('blocked', 'Blocked'), ('invalid', 'Invalid address'), ('invitation_opt_out', 'Opted out of invitations')], max_length=32)),
                ('source', models.CharField(choices=[('provider', 'Email provider'), ('recipient', 'Recipient'), ('admin', 'Admin')], max_length=16)),
                ('detail', models.TextField(blank=True, default='', help_text='Provider reason text.')),
                ('organization', models.ForeignKey(blank=True, help_text='Organization whose mail triggered the suppression, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.organization')),
            ],
            options={
                'verbose_name': 'Email Suppression',
                'verbose_name_plural': 'Email Suppressions',
            },
        ),
    ]
