from decouple import config

from .base import DEBUG, REDIS_HOST, TIME_ZONE

CELERY_REDIS_DB = config("CELERY_REDIS_DB", default=0, cast=int)

# CELERY
CELERY_BROKER_URL = f"redis://{REDIS_HOST}:6379/{CELERY_REDIS_DB}"
CELERY_ACCEPT_CONTENT = ["application/json"]
CELERY_RESULT_EXTENDED = True
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_RESULT_BACKEND = "django-db"
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_ALWAYS_EAGER = config("CELERY_TASK_ALWAYS_EAGER", cast=bool, default=DEBUG)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

