# Generated by Django 5.2.17 on 2026-09-05 10:28

import django.db.models.deletion
import encrypted_fields.fields
import integrations.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0117_tickettier_sales_paused'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformConnection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('provider', models.CharField(max_length=32)),
                ('access_token', encrypted_fields.fields.EncryptedTextField()),
                ('refresh_token', encrypted_fields.fields.EncryptedTextField(blank=True, null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('remote_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('remote_account_name', models.CharField(blank=True, default='', max_length=255)),
                ('auto_sync', models.BooleanField(default=False, help_text='Org-wide default; EventLink.auto_sync overrides per event.')),
                ('webhook_remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('webhook_secret', models.CharField(default=integrations.models.new_webhook_secret, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending account selection'), ('active', 'Active'), ('revoked', 'Revoked'), ('error', 'Error')], db_index=True, default='pending', max_length=16)),
                ('last_error', models.JSONField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_connections', to='events.organization')),
            ],
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remote_id', models.CharField(blank=True, default='', max_length=255)),
                ('remote_url', models.URLField(blank=True, default='')),
                ('auto_sync', models.BooleanField(blank=True, help_text='Null = inherit the connection default.', null=True)),
                ('remote_status', models.CharField(choices=[('draft', 'Draft'), ('live', 'Live'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('sync_state', models.CharField(choices=[('in_sync', 'In sync'), ('pending', 'Pending'), ('failed', 'Failed'), ('broken', 'Broken (remote deleted)')], db_index=True, default='pending', max_length=16)),
                ('origin', models.CharField(choices=[('pushed', 'Pushed from Revel'), ('imported', 'Imported from platform')], default='pushed', max_length=16)),
                ('last_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_pulled_at', models.DateTimeField(blank=True, null=True)),
                ('sync_report', models.JSONField(blank=True, default=list)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to='events.event')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_links', to='integrations.platformconnection')),
            ],
        ),
        migrations.CreateModel(
            name='TierLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('remote_id', models.CharField(max_length=255)),
                ('remote_quantity_sold', models.PositiveIntegerField(default=0)),
                ('counts_updated_at', models.DateTimeField(blank=True, null=True)),
                ('remote_paused', models.BooleanField(default=False, help_text='What Revel last set; the mapper reads this on every push.')),
                ('last_error', models.JSONField(blank=True, null=True)),
                ('event_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_links', to='integrations.eventlink')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_links', to='events.tickettier')),
            ],
        ),
        migrations.CreateModel(
            name='WebhookDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('resource_path', models.CharField(blank=True, default='', max_length=512)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_deliveries', to='integrations.platformconnection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='platformconnection',
            constraint=models.UniqueConstraint(fields=('organization', 'provider'), name='unique_connection_per_provider'),
        ),
        migrations.AddConstraint(
            model_name='eventlink',
            constraint=models.UniqueConstraint(fields=('event', 'connection'), name='unique_link_per_connection'),
        ),
        migrations.AddConstraint(
            model_name='tierlink',
            constraint=models.UniqueConstraint(fields=('tier', 'event_link'), name='unique_tier_link_per_event_link'),
        ),
    ]
