"""Unfold admin for the swapped Application and DOT's token models (spec §8, §16).

Nothing here is registered with ``@admin.register``. DOT's own ``oauth2_provider/admin.py``
registers all five models from the five ``*_ADMIN_CLASS`` settings in
``revel/settings/oauth.py``, which is why those settings had to wait for this module to exist
(R-01) and why ``oauth/tests/test_admin.py`` asserts the registry really holds these classes.

Unfold comes first in every MRO so its templates and widgets win over DOT's plain
``ModelAdmin`` (repo precedent: ``events/admin/announcement.py``).
"""

import typing as t

from django.contrib import admin
from django.http import HttpRequest
from django.utils.translation import gettext_lazy as _
from oauth2_provider.admin import AccessTokenAdmin, ApplicationAdmin, GrantAdmin, IDTokenAdmin, RefreshTokenAdmin
from oauth2_provider.settings import oauth2_settings
from unfold.admin import ModelAdmin

from oauth.models import OAuthApplication
from oauth.service import token_service

#: Characters of the lookup checksum shown in the credential changelists. Enough to correlate a
#: row with a log line, and not a credential: the checksum is a SHA-256 of the bearer, so a
#: prefix of it cannot be reversed into one.
_CHECKSUM_PREFIX_LENGTH = 8

#: Shown on ``algorithm`` when no signing key is configured. With the provider off there is no
#: valid value for the field at all — DOT's ``clean()`` refuses RS256 without
#: ``OIDC_RSA_PRIVATE_KEY`` and its ``NO_ALGORITHM`` is ``""``, which our ``blank=False`` field
#: refuses in turn. That is the credential-presence feature flag working as designed (ADR-0008,
#: R-36/R-98), so the help text explains it instead of the operator rediscovering it from a
#: validation error (#986).
_NO_SIGNING_KEY_HELP = _(
    "The OAuth provider has no signing key configured, so no application can be saved: "
    "RS256 requires OIDC_SIGNING_KEY_PATH to point at an RSA private key PEM, and the "
    '"no algorithm" option is not accepted for this field. Configure the key first.'
)


class OAuthApplicationAdmin(ModelAdmin, ApplicationAdmin):  # type: ignore[misc]
    """The registered clients, with a revocation hook on deactivation."""

    list_display = (
        "name",
        "client_id",
        "user",
        "client_type",
        "registration_source",
        "verified",
        "is_active",
        "last_used_at",
    )
    list_filter = ("registration_source", "client_type", "verified", "is_active")
    search_fields = ("name", "client_id", "user__email")
    # ``registration_source`` and ``cimd_expires_at`` are DOT's own readonly set and are kept
    # here deliberately: ``registration_source`` is a security boundary (the RFC 7592 management
    # endpoint only operates on DCR-registered apps), so overriding the tuple without them would
    # silently make a manual app promotable into that code path. ``client_secret`` is a stored
    # hash, not a usable credential, and is rotated through the API's rotate-secret endpoint.
    readonly_fields = (
        "registration_source",
        "cimd_expires_at",
        "client_id",
        "client_secret",
        # Generated by ``common.service.upload_service`` from ``logo``, never typed.
        "logo_thumbnail",
        "last_used_at",
        "created",
        "updated",
    )

    def get_form(self, request: HttpRequest, obj: t.Any = None, change: bool = False, **kwargs: t.Any) -> t.Any:
        """Explain an unconfigured provider on the field that will reject the save.

        Args:
            request: The admin request.
            obj: The instance being edited, or None on the add form.
            change: Whether this is a change form.
            **kwargs: Passed through to ``modelform_factory``.

        Returns:
            The model form class.
        """
        if not oauth2_settings.OIDC_RSA_PRIVATE_KEY:
            kwargs["help_texts"] = {"algorithm": _NO_SIGNING_KEY_HELP, **kwargs.get("help_texts", {})}
        return super().get_form(request, obj, change=change, **kwargs)

    def save_model(self, request: HttpRequest, obj: OAuthApplication, form: t.Any, change: bool) -> None:
        """Save, then make the edit reach DOT's tables when it withdrew authority.

        Two edits withdraw authority and so must revoke, or the admin and
        ``app_service`` disagree about what the same edit means (R-115):

        * **Deactivation.** ``is_usable()`` already refuses a deactivated app at request time,
          so this is not what locks the client out — it is what stops a re-activation
          resurrecting live credentials, and what stops ``authorize_service.has_prior_grant``
          treating the surviving refresh tokens as a prior grant and silently re-approving.
        * **Scope shrink.** ``common.authentication`` builds a principal from the scope string
          stored at issue time rather than the app's current ``allowed_scopes``, *because*
          narrowing those is supposed to revoke the live tokens. ``save()`` deliberately does
          not re-seed ``allowed_scopes`` on update, so without this an admin could withdraw a
          scope and leave every token still carrying it.

        Args:
            request: The admin request.
            obj: The application being saved.
            form: The bound admin form; ``initial`` holds the pre-edit values.
            change: False on an add, where there is nothing yet to revoke.
        """
        super().save_model(request, obj, form, change)
        if not change:
            return
        if "is_active" in form.changed_data and not obj.is_active:
            token_service.revoke_app_tokens(obj)
        if "allowed_scopes" in form.changed_data:
            removed = set(form.initial.get("allowed_scopes") or []) - set(obj.allowed_scopes or [])
            if removed:
                token_service.revoke_scoped_tokens(obj, removed)


class _ReadOnlyCredentialAdmin(ModelAdmin):  # type: ignore[misc]
    """Unfold base for DOT's credential tables, with **every** field forced readonly (R-113).

    DOT already disables add and delete on these admins, deliberately making them
    view-and-revoke surfaces. But *change* stays open, and one editable field on it is a mint:
    under ``COMPLIANT_BCP_RFC9700_TOKEN_STORAGE`` (on here) the ``token`` column is stored
    blank, so ``token_checksum`` is the sole bearer verifier —
    ``OAuth2Validator._load_access_token`` filters on it alone — and
    ``TokenChecksumField.pre_save`` keeps a hand-typed value verbatim when there is no raw token
    to recompute from. A staff user with ``change_accesstoken`` could paste
    ``sha256(<secret>)`` and set ``user``, ``scope`` and ``expires`` on the same page, then call
    the API as that user. On the refresh admin the same edit clears ``revoked`` back to NULL and
    re-arms ``has_prior_grant``.

    Readonly is computed from ``_meta.fields`` rather than enumerated, so a field added by a DOT
    upgrade is covered by construction rather than by someone remembering to list it. Revocation
    stays available through DOT's own ``revoke_tokens`` action, which is the point of the screen.
    """

    def get_readonly_fields(self, request: HttpRequest, obj: t.Any = None) -> tuple[str, ...]:
        """Every concrete field, plus whatever DOT adds, minus whatever DOT excludes.

        The exclusions matter: DOT hides ``token``/``code`` on the change form, and a field that
        is both excluded and readonly is *rendered* by the admin — which would display the very
        cleartext credential the exclusion exists to hide on a deployment that has turned
        RFC 9700 token storage off.

        Args:
            request: The admin request.
            obj: The instance being viewed, or None.

        Returns:
            The readonly field names, in a stable order.
        """
        excluded = set(self.get_exclude(request, obj) or ())
        inherited = (name for name in super().get_readonly_fields(request, obj) if name not in excluded)
        concrete = (f.name for f in self.model._meta.fields if f.name not in excluded)
        return tuple(dict.fromkeys((*inherited, *concrete)))


class _ChecksumMaskedTokenAdmin(_ReadOnlyCredentialAdmin):
    """Shows a checksum prefix where DOT shows a masked token.

    DOT's ``masked_token`` reads the ``token`` column, which RFC 9700 storage leaves blank, and
    ``mask_credential("")`` returns ``""`` — so the column is permanently empty and cannot do
    the one job a masked credential has, which is to let an operator correlate a row.
    """

    @admin.display(description=_("token checksum"))
    def masked_token(self, obj: t.Any) -> str:
        """A short prefix of the lookup checksum, never the token.

        Args:
            obj: The token row, or None in an empty changelist cell.

        Returns:
            The prefix, or an empty string when there is no row.
        """
        if obj is None:
            return ""
        return str(obj.token_checksum[:_CHECKSUM_PREFIX_LENGTH])


class OAuthAccessTokenAdmin(_ChecksumMaskedTokenAdmin, AccessTokenAdmin):  # type: ignore[misc]
    """DOT's access-token admin under Unfold: view, correlate, revoke. Nothing editable."""


class OAuthGrantAdmin(_ReadOnlyCredentialAdmin, GrantAdmin):  # type: ignore[misc]
    """DOT's grant admin under Unfold. ``code`` is stored in cleartext, so DOT's mask stands."""


class OAuthIDTokenAdmin(_ReadOnlyCredentialAdmin, IDTokenAdmin):  # type: ignore[misc]
    """DOT's ID-token admin under Unfold."""


class OAuthRefreshTokenAdmin(_ChecksumMaskedTokenAdmin, RefreshTokenAdmin):  # type: ignore[misc]
    """DOT's refresh-token admin under Unfold; its revoke action keeps the reuse tombstone."""
