# Generated by Django 5.2.14 on 2026-05-21 21:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0075_nudge_periodic_task'),
        ('questionnaires', '0012_alter_questionnaire_llm_backend'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], db_index=True, default='draft', max_length=10)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closes_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('allow_vote_changes', models.BooleanField(default=False)),
                ('vote_visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only'), ('attendees-only', 'Attendees Only')], db_index=True, max_length=20)),
                ('result_visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only'), ('attendees-only', 'Attendees Only')], default='staff-only', max_length=20)),
                ('result_timing', models.CharField(choices=[('after_vote', 'After vote'), ('after_close', 'After close'), ('never', 'Never')], default='never', max_length=20)),
                ('staff_anonymous', models.BooleanField(default=True)),
                ('public_anonymous', models.BooleanField(default=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='events.organization')),
                ('questionnaire', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll', to='questionnaires.questionnaire')),
                ('result_membership_tiers', models.ManyToManyField(blank=True, related_name='results_visible_polls', to='events.membershiptier')),
                ('vote_membership_tiers', models.ManyToManyField(blank=True, related_name='voteable_polls', to='events.membershiptier')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('result_visibility__in', ['public', 'unlisted']), _negated=True), ('public_anonymous', True), _connector='OR'), name='poll_public_results_must_be_anonymous'), models.CheckConstraint(condition=models.Q(models.Q(models.Q(('vote_visibility__in', ['private', 'attendees-only']), _negated=True), models.Q(('result_visibility__in', ['private', 'attendees-only']), _negated=True)), ('event__isnull', False), _connector='OR'), name='poll_restricted_visibility_requires_event')],
            },
        ),
    ]
