"""Events schema package.

This package contains all schema definitions for the events app,
organized into modules that mirror the models package structure.

All schemas are re-exported here for backward compatibility.
"""

# Mixins and utilities
# Announcement schemas
from .announcement import (
    AnnouncementCreateSchema,
    AnnouncementListSchema,
    AnnouncementPublicSchema,
    AnnouncementScheduleSchema,
    AnnouncementSchema,
    AnnouncementUpdateSchema,
    RecipientCountSchema,
)

# Application schemas
from .application import (
    ApplyRequestSchema,
    ApplyResponseSchema,
    JoinEligibilityQuery,
    MembershipApplicationSchema,
    MembershipEligibilitySchema,
)

# Blacklist schemas
from .blacklist import (
    BlacklistCreateSchema,
    BlacklistEntrySchema,
    BlacklistUpdateSchema,
    WhitelistEntrySchema,
    WhitelistRequestCreateSchema,
    WhitelistRequestSchema,
)
from .bookmark import EventBookmarkSchema

# Dietary schemas
from .dietary import (
    AggregatedDietaryPreferenceSchema,
    AggregatedDietaryRestrictionSchema,
    EventDietarySummarySchema,
)

# Discount code schemas
from .discount_code import (
    DiscountCodeCreateSchema,
    DiscountCodeDeleteResponse,
    DiscountCodeSchema,
    DiscountCodeUpdateSchema,
    DiscountCodeValidationResponse,
    DiscountCodeValidationSchema,
)

# Event schemas
from .event import (
    AttendeeSchema,
    EventCreateSchema,
    EventDetailSchema,
    EventDuplicateSchema,
    EventEditSchema,
    EventEditSlugSchema,
    EventInListSchema,
    EventScheduleSessionSchema,
    EventScheduleUpdateSchema,
    EventStatusUpdatePayload,
    EventVisibilitySettingsSchema,
    MinimalEventSchema,
    SeriesPassLinkInputSchema,
    TagUpdateSchema,
)

# Event series schemas
from .event_series import (
    EventSeriesEditSchema,
    EventSeriesInListSchema,
    EventSeriesRetrieveSchema,
    MinimalEventSeriesSchema,
)

# Export schemas
from .export import (
    FileExportSchema,
)

# Financials schemas
from .financials import (
    CombinedTotalsSchema,
    CurrencyFinancialsSchema,
    EventFinancialsSchema,
    MembershipFinancialsSchema,
    OrganizationFinancialsSchema,
    RateBucketSchema,
)

# Follow schemas
from .follow import (
    EventSeriesFollowCreateSchema,
    EventSeriesFollowSchema,
    EventSeriesFollowStatusSchema,
    EventSeriesFollowUpdateSchema,
    MinimalEventSeriesFollowSchema,
    MinimalOrganizationFollowSchema,
    OrganizationFollowCreateSchema,
    OrganizationFollowSchema,
    OrganizationFollowStatusSchema,
    OrganizationFollowUpdateSchema,
)

# Invitation schemas
from .invitation import (
    CombinedInvitationListSchema,
    DirectInvitationCreateSchema,
    DirectInvitationResponseSchema,
    EventInvitationListSchema,
    EventInvitationRequestCreateSchema,
    EventInvitationRequestInternalSchema,
    EventInvitationRequestSchema,
    EventTokenCreateSchema,
    EventTokenRejectionSchema,
    EventTokenSchema,
    EventTokenUpdateSchema,
    InvitationBaseSchema,
    InvitationSchema,
    MyEventInvitationSchema,
    PendingEventInvitationListSchema,
)

# Invoice schemas
from .invoice import (
    AttendeeInvoiceCreditNoteSchema,
    AttendeeInvoiceDetailSchema,
    AttendeeInvoiceSchema,
    InvoiceDownloadURLSchema,
    InvoiceLineItemSchema,
    InvoicingModeUpdateSchema,
    PlatformFeeCreditNoteSchema,
    PlatformFeeInvoiceSchema,
    UpdateAttendeeInvoiceSchema,
)

# Misc schemas
from .misc import (
    AdditionalResourceCreateSchema,
    AdditionalResourceSchema,
    AdditionalResourceUpdateSchema,
)
from .mixins import (
    CityEditMixin,
    SocialMediaSchemaEditMixin,
    SocialMediaSchemaRetrieveMixin,
)

# Organization schemas
from .organization import (
    ApproveMembershipRequestSchema,
    MemberAddSchema,
    MembershipApplicationSubmissionInfo,
    MembershipTierAdminSchema,
    MembershipTierCreateSchema,
    MembershipTierSchema,
    MembershipTierUpdateSchema,
    MinimalOrganizationMemberSchema,
    MinimalOrganizationSchema,
    OrganizationAdminDetailSchema,
    OrganizationBillingInfoSchema,
    OrganizationBillingInfoUpdateSchema,
    OrganizationContactMessageCreateSchema,
    OrganizationContactMessageSchema,
    OrganizationCreateSchema,
    OrganizationEditSchema,
    OrganizationInListSchema,
    OrganizationMembershipRequestCreateSchema,
    OrganizationMembershipRequestRetrieve,
    OrganizationMemberUpdateSchema,
    OrganizationPermissionsSchema,
    OrganizationRetrieveSchema,
    OrganizationStaffSchema,
    OrganizationTokenCreateSchema,
    OrganizationTokenRejectionSchema,
    OrganizationTokenSchema,
    OrganizationTokenUpdateSchema,
    StaffAddSchema,
    VATIdUpdateSchema,
    VerifyOrganizationContactEmailJWTPayloadSchema,
)

# Potluck schemas
from .potluck import (
    PotluckItemCreateSchema,
    PotluckItemRetrieveSchema,
)

# Preferences schemas
from .preferences import (
    GeneralUserPreferencesSchema,
    GeneralUserPreferencesUpdateSchema,
)

# Pronoun schemas
from .pronouns import (
    EventPronounDistributionSchema,
    PronounCountSchema,
)

# Questionnaire schemas
from .questionnaire import (
    EventAssignmentSchema,
    EventSeriesAssignmentSchema,
    McOptionStatSchema,
    McQuestionStatSchema,
    OrganizationQuestionnaireCreateSchema,
    OrganizationQuestionnaireInListSchema,
    OrganizationQuestionnaireSchema,
    OrganizationQuestionnaireUpdateSchema,
    QuestionnaireDuplicateSchema,
    QuestionnaireSummarySchema,
    ScoreStatsSchema,
    StatusBreakdownSchema,
)

# Recurrence rule schemas
from .recurrence_rule import (
    RecurrenceRuleCreateSchema,
    RecurrenceRuleSchema,
    RecurrenceRuleUpdateSchema,
)

# Recurring event schemas
from .recurring_event import (
    CancelOccurrenceSchema,
    EventSeriesDriftSchema,
    EventSeriesRecurrenceDetailSchema,
    EventSeriesRecurrenceUpdateSchema,
    GenerateSeriesEventsSchema,
    RecurringEventCreateSchema,
    TemplateEditSchema,
)

# Revenue report schemas
from .revenue_report import RevenueReportRequestSchema

# RSVP schemas
from .rsvp import (
    EventRSVPSchema,
    EventUserStatusResponse,
    GuestRSVPRequestSchema,
    RSVPCreateSchema,
    RSVPDetailSchema,
    RSVPNoteSchema,
    RSVPUpdateSchema,
    TierRemainingTicketsSchema,
    UserRSVPSchema,
    WaitlistEntrySchema,
)

# Seating schemas
from .seating import (
    BestAvailableHoldRequest,
    BoxOfficeReseatRequest,
    BoxOfficeSellRequest,
    ChartSeatSchema,
    ChartSectorSchema,
    HoldConflictReason,
    HoldResponseSchema,
    HoldSeatsRequest,
    ReleaseSeatsRequest,
    SeatingAvailabilitySchema,
    SeatOverrideItemSchema,
    SeatOverridesRequest,
    SeatOverridesResponse,
    StandingAvailabilitySchema,
    VenueChartSchema,
    ZoneAvailabilitySchema,
)

# Series pass schemas
from .series_pass import (
    HeldSeriesPassAdminSchema,
    HeldSeriesPassCancelSchema,
    HeldSeriesPassSchema,
    SeriesPassAdminSchema,
    SeriesPassCheckoutResponseSchema,
    SeriesPassCreateSchema,
    SeriesPassQuoteSchema,
    SeriesPassSchema,
    SeriesPassSeriesInfoSchema,
    SeriesPassTierLinkAdminSchema,
    SeriesPassTierLinkInputSchema,
    SeriesPassUpdateSchema,
)

# Subscription schemas
from .subscription import (
    BillingPortalRequestSchema,
    BillingPortalSessionSchema,
    CancelSubscriptionSchema,
    ChangePlanRequestSchema,
    MemberCancelSubscriptionSchema,
    MemberPlanSchema,
    MembershipPaymentSchema,
    MigrationAcceptedSchema,
    MyMembershipPaymentSchema,
    MyMembershipSchema,
    MySubscriptionSchema,
    OrganizationMemberSchema,
    OrganizationMembershipPaymentSchema,
    PaymentRecordSchema,
    PlanCreateSchema,
    PlanSchema,
    PlanUpdateSchema,
    PublicPlanSchema,
    RefundSchema,
    RevivalRequestSchema,
    RevivalResponseSchema,
    StaffRevivalResponseSchema,
    SubscribeRequestSchema,
    SubscribeResponseSchema,
    SubscriptionActivationPendingSchema,
    SubscriptionCreateSchema,
    SubscriptionMetricsSchema,
    SubscriptionSchema,
    SubscriptionStatusBreakdownSchema,
)

# Ticket and payment schemas
from .ticket import (
    AdminCancelTicketSchema,
    AdminRefundTicketSchema,
    AdminTicketSchema,
    BatchCheckoutPayload,
    BatchCheckoutPWYCPayload,
    BatchCheckoutResponse,
    BuyerBillingInfoSchema,
    CancellationBlockedErrorSchema,
    CancellationPreviewSchema,
    CheckInRequestSchema,
    CheckInResponseSchema,
    CheckoutSessionResponse,
    ConfirmPaymentSchema,
    Currencies,
    GuestActionConfirmSchema,
    GuestActionPayload,
    GuestActionResponseSchema,
    GuestBatchCheckoutPayload,
    GuestBatchCheckoutPWYCPayload,
    GuestCheckoutResponseSchema,
    GuestPWYCCheckoutSchema,
    GuestRSVPJWTPayloadSchema,
    GuestTicketItemPayload,
    GuestTicketJWTPayloadSchema,
    GuestUserDataSchema,
    PaymentSchema,
    PWYCCheckoutPayloadSchema,
    RefundPolicySchema,
    RefundPolicyTierSchema,
    RefundWindowSchema,
    ReorderSchema,
    StripeAccountStatusSchema,
    StripeCheckoutSessionSchema,
    StripeOnboardingLinkSchema,
    TicketCancellationRequestSchema,
    TicketCancellationResponseSchema,
    TicketDiscountCodeSchema,
    TicketPurchaseItem,
    TicketSeriesPassSchema,
    TicketTierCreateSchema,
    TicketTierDetailSchema,
    TicketTierSchema,
    TicketTierUpdateSchema,
    TierCategoryPriceSchema,
    TierSeatPricingSchema,
    UserTicketSchema,
    VATPreviewItemSchema,
    VATPreviewLineItemSchema,
    VATPreviewRequestSchema,
    VATPreviewResponseSchema,
)

# Venue schemas
from .venue import (
    AffectedTierSchema,
    Coordinate2D,
    MinimalSeatSchema,
    PolygonShape,
    PriceCategoryCreateSchema,
    PriceCategorySchema,
    PriceCategoryUpdateSchema,
    SeatPaintResultSchema,
    SeatPriceChangeSchema,
    SectorAvailabilitySchema,
    TierPricingGapSchema,
    TierUnsellableZoneSchema,
    UnsellableZoneTierSchema,
    VenueAvailabilitySchema,
    VenueCreateSchema,
    VenueDetailSchema,
    VenueSchema,
    VenueSeatBulkCreateSchema,
    VenueSeatBulkDeleteSchema,
    VenueSeatBulkUpdateItemSchema,
    VenueSeatBulkUpdateSchema,
    VenueSeatInputSchema,
    VenueSeatPaintSchema,
    VenueSeatSchema,
    VenueSeatUpdateSchema,
    VenueSectorCreateSchema,
    VenueSectorSchema,
    VenueSectorUpdateSchema,
    VenueSectorWithSeatsSchema,
    VenueUpdateSchema,
    VenueWithSeatsSchema,
    point_in_polygon,
)

# Waitlist (advanced) schemas
from .waitlist import (
    WaitlistOfferCreateSchema,
    WaitlistOfferReactivateSchema,
    WaitlistOfferSchema,
    WaitlistSettingsSchema,
    WaitlistSettingsUpdateSchema,
)

__all__ = [
    "AdditionalResourceCreateSchema",
    "AdditionalResourceSchema",
    "AdditionalResourceUpdateSchema",
    "AdminCancelTicketSchema",
    "AdminRefundTicketSchema",
    "AdminTicketSchema",
    "AffectedTierSchema",
    "AggregatedDietaryPreferenceSchema",
    "AggregatedDietaryRestrictionSchema",
    "AnnouncementCreateSchema",
    "AnnouncementListSchema",
    "AnnouncementPublicSchema",
    "AnnouncementScheduleSchema",
    "AnnouncementSchema",
    "AnnouncementUpdateSchema",
    "ApplyRequestSchema",
    "ApplyResponseSchema",
    "ApproveMembershipRequestSchema",
    "AttendeeInvoiceCreditNoteSchema",
    "AttendeeInvoiceDetailSchema",
    "AttendeeInvoiceSchema",
    "AttendeeSchema",
    "BatchCheckoutPWYCPayload",
    "BatchCheckoutPayload",
    "BatchCheckoutResponse",
    "BestAvailableHoldRequest",
    "BillingPortalRequestSchema",
    "BillingPortalSessionSchema",
    "BlacklistCreateSchema",
    "BlacklistEntrySchema",
    "BlacklistUpdateSchema",
    "BoxOfficeReseatRequest",
    "BoxOfficeSellRequest",
    "BuyerBillingInfoSchema",
    "CancelOccurrenceSchema",
    "CancelSubscriptionSchema",
    "CancellationBlockedErrorSchema",
    "CancellationPreviewSchema",
    "ChangePlanRequestSchema",
    "ChartSeatSchema",
    "ChartSectorSchema",
    "CheckInRequestSchema",
    "CheckInResponseSchema",
    "CheckoutSessionResponse",
    "CityEditMixin",
    "CombinedInvitationListSchema",
    "CombinedTotalsSchema",
    "ConfirmPaymentSchema",
    "Coordinate2D",
    "Currencies",
    "CurrencyFinancialsSchema",
    "DirectInvitationCreateSchema",
    "DirectInvitationResponseSchema",
    "DiscountCodeCreateSchema",
    "DiscountCodeDeleteResponse",
    "DiscountCodeSchema",
    "DiscountCodeUpdateSchema",
    "DiscountCodeValidationResponse",
    "DiscountCodeValidationSchema",
    "EventAssignmentSchema",
    "EventBookmarkSchema",
    "EventCreateSchema",
    "EventDetailSchema",
    "EventDietarySummarySchema",
    "EventDuplicateSchema",
    "EventEditSchema",
    "EventEditSlugSchema",
    "EventFinancialsSchema",
    "EventInListSchema",
    "EventInvitationListSchema",
    "EventInvitationRequestCreateSchema",
    "EventInvitationRequestInternalSchema",
    "EventInvitationRequestSchema",
    "EventPronounDistributionSchema",
    "EventRSVPSchema",
    "EventScheduleSessionSchema",
    "EventScheduleUpdateSchema",
    "EventSeriesAssignmentSchema",
    "EventSeriesDriftSchema",
    "EventSeriesEditSchema",
    "EventSeriesFollowCreateSchema",
    "EventSeriesFollowSchema",
    "EventSeriesFollowStatusSchema",
    "EventSeriesFollowUpdateSchema",
    "EventSeriesInListSchema",
    "EventSeriesRecurrenceDetailSchema",
    "EventSeriesRecurrenceUpdateSchema",
    "EventSeriesRetrieveSchema",
    "EventStatusUpdatePayload",
    "EventTokenCreateSchema",
    "EventTokenRejectionSchema",
    "EventTokenSchema",
    "EventTokenUpdateSchema",
    "EventUserStatusResponse",
    "EventVisibilitySettingsSchema",
    "FileExportSchema",
    "GeneralUserPreferencesSchema",
    "GeneralUserPreferencesUpdateSchema",
    "GenerateSeriesEventsSchema",
    "GuestActionConfirmSchema",
    "GuestActionPayload",
    "GuestActionResponseSchema",
    "GuestBatchCheckoutPWYCPayload",
    "GuestBatchCheckoutPayload",
    "GuestCheckoutResponseSchema",
    "GuestPWYCCheckoutSchema",
    "GuestRSVPJWTPayloadSchema",
    "GuestRSVPRequestSchema",
    "GuestTicketItemPayload",
    "GuestTicketJWTPayloadSchema",
    "GuestUserDataSchema",
    "HeldSeriesPassAdminSchema",
    "HeldSeriesPassCancelSchema",
    "HeldSeriesPassSchema",
    "HoldConflictReason",
    "HoldResponseSchema",
    "HoldSeatsRequest",
    "InvitationBaseSchema",
    "InvitationSchema",
    "InvoiceDownloadURLSchema",
    "InvoiceLineItemSchema",
    "InvoicingModeUpdateSchema",
    "JoinEligibilityQuery",
    "McOptionStatSchema",
    "McQuestionStatSchema",
    "MemberAddSchema",
    "MemberCancelSubscriptionSchema",
    "MemberPlanSchema",
    "MembershipApplicationSchema",
    "MembershipApplicationSubmissionInfo",
    "MembershipEligibilitySchema",
    "MembershipFinancialsSchema",
    "MembershipPaymentSchema",
    "MembershipTierAdminSchema",
    "MembershipTierCreateSchema",
    "MembershipTierSchema",
    "MembershipTierUpdateSchema",
    "MigrationAcceptedSchema",
    "MinimalEventSchema",
    "MinimalEventSeriesFollowSchema",
    "MinimalEventSeriesSchema",
    "MinimalOrganizationFollowSchema",
    "MinimalOrganizationMemberSchema",
    "MinimalOrganizationSchema",
    "MinimalSeatSchema",
    "MyEventInvitationSchema",
    "MyMembershipPaymentSchema",
    "MyMembershipSchema",
    "MySubscriptionSchema",
    "OrganizationAdminDetailSchema",
    "OrganizationBillingInfoSchema",
    "OrganizationBillingInfoUpdateSchema",
    "OrganizationContactMessageCreateSchema",
    "OrganizationContactMessageSchema",
    "OrganizationCreateSchema",
    "OrganizationEditSchema",
    "OrganizationFinancialsSchema",
    "OrganizationFollowCreateSchema",
    "OrganizationFollowSchema",
    "OrganizationFollowStatusSchema",
    "OrganizationFollowUpdateSchema",
    "OrganizationInListSchema",
    "OrganizationMemberSchema",
    "OrganizationMemberUpdateSchema",
    "OrganizationMembershipPaymentSchema",
    "OrganizationMembershipRequestCreateSchema",
    "OrganizationMembershipRequestRetrieve",
    "OrganizationPermissionsSchema",
    "OrganizationQuestionnaireCreateSchema",
    "OrganizationQuestionnaireInListSchema",
    "OrganizationQuestionnaireSchema",
    "OrganizationQuestionnaireUpdateSchema",
    "OrganizationRetrieveSchema",
    "OrganizationStaffSchema",
    "OrganizationTokenCreateSchema",
    "OrganizationTokenRejectionSchema",
    "OrganizationTokenSchema",
    "OrganizationTokenUpdateSchema",
    "PWYCCheckoutPayloadSchema",
    "PaymentRecordSchema",
    "PaymentSchema",
    "PendingEventInvitationListSchema",
    "PlanCreateSchema",
    "PlanSchema",
    "PlanUpdateSchema",
    "PlatformFeeCreditNoteSchema",
    "PlatformFeeInvoiceSchema",
    "PolygonShape",
    "PotluckItemCreateSchema",
    "PotluckItemRetrieveSchema",
    "PriceCategoryCreateSchema",
    "PriceCategorySchema",
    "PriceCategoryUpdateSchema",
    "PronounCountSchema",
    "PublicPlanSchema",
    "QuestionnaireDuplicateSchema",
    "QuestionnaireSummarySchema",
    "RSVPCreateSchema",
    "RSVPDetailSchema",
    "RSVPNoteSchema",
    "RSVPUpdateSchema",
    "RateBucketSchema",
    "RecipientCountSchema",
    "RecurrenceRuleCreateSchema",
    "RecurrenceRuleSchema",
    "RecurrenceRuleUpdateSchema",
    "RecurringEventCreateSchema",
    "RefundPolicySchema",
    "RefundPolicyTierSchema",
    "RefundSchema",
    "RefundWindowSchema",
    "ReleaseSeatsRequest",
    "ReorderSchema",
    "RevenueReportRequestSchema",
    "RevivalRequestSchema",
    "RevivalResponseSchema",
    "ScoreStatsSchema",
    "SeatOverrideItemSchema",
    "SeatOverridesRequest",
    "SeatOverridesResponse",
    "SeatPaintResultSchema",
    "SeatPriceChangeSchema",
    "SeatingAvailabilitySchema",
    "SectorAvailabilitySchema",
    "SeriesPassAdminSchema",
    "SeriesPassCheckoutResponseSchema",
    "SeriesPassCreateSchema",
    "SeriesPassLinkInputSchema",
    "SeriesPassQuoteSchema",
    "SeriesPassSchema",
    "SeriesPassSeriesInfoSchema",
    "SeriesPassTierLinkAdminSchema",
    "SeriesPassTierLinkInputSchema",
    "SeriesPassUpdateSchema",
    "SocialMediaSchemaEditMixin",
    "SocialMediaSchemaRetrieveMixin",
    "StaffAddSchema",
    "StaffRevivalResponseSchema",
    "StandingAvailabilitySchema",
    "StatusBreakdownSchema",
    "StripeAccountStatusSchema",
    "StripeCheckoutSessionSchema",
    "StripeOnboardingLinkSchema",
    "SubscribeRequestSchema",
    "SubscribeResponseSchema",
    "SubscriptionActivationPendingSchema",
    "SubscriptionCreateSchema",
    "SubscriptionMetricsSchema",
    "SubscriptionSchema",
    "SubscriptionStatusBreakdownSchema",
    "TagUpdateSchema",
    "TemplateEditSchema",
    "TicketCancellationRequestSchema",
    "TicketCancellationResponseSchema",
    "TicketDiscountCodeSchema",
    "TicketPurchaseItem",
    "TicketSeriesPassSchema",
    "TicketTierCreateSchema",
    "TicketTierDetailSchema",
    "TicketTierSchema",
    "TicketTierUpdateSchema",
    "TierCategoryPriceSchema",
    "TierPricingGapSchema",
    "TierRemainingTicketsSchema",
    "TierSeatPricingSchema",
    "TierUnsellableZoneSchema",
    "UnsellableZoneTierSchema",
    "UpdateAttendeeInvoiceSchema",
    "UserRSVPSchema",
    "UserTicketSchema",
    "VATIdUpdateSchema",
    "VATPreviewItemSchema",
    "VATPreviewLineItemSchema",
    "VATPreviewRequestSchema",
    "VATPreviewResponseSchema",
    "VenueAvailabilitySchema",
    "VenueChartSchema",
    "VenueCreateSchema",
    "VenueDetailSchema",
    "VenueSchema",
    "VenueSeatBulkCreateSchema",
    "VenueSeatBulkDeleteSchema",
    "VenueSeatBulkUpdateItemSchema",
    "VenueSeatBulkUpdateSchema",
    "VenueSeatInputSchema",
    "VenueSeatPaintSchema",
    "VenueSeatSchema",
    "VenueSeatUpdateSchema",
    "VenueSectorCreateSchema",
    "VenueSectorSchema",
    "VenueSectorUpdateSchema",
    "VenueSectorWithSeatsSchema",
    "VenueUpdateSchema",
    "VenueWithSeatsSchema",
    "VerifyOrganizationContactEmailJWTPayloadSchema",
    "WaitlistEntrySchema",
    "WaitlistOfferCreateSchema",
    "WaitlistOfferReactivateSchema",
    "WaitlistOfferSchema",
    "WaitlistSettingsSchema",
    "WaitlistSettingsUpdateSchema",
    "WhitelistEntrySchema",
    "WhitelistRequestCreateSchema",
    "WhitelistRequestSchema",
    "ZoneAvailabilitySchema",
    "point_in_polygon",
]
