# Generated by Django 5.2.3 on 2025-10-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reveluser',
            options={'ordering': ['username']},
        ),
    ]
