# Generated by Django 5.2.3 on 2025-10-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_reveluser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveluser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('it', 'Italiano')], db_index=True, default='en', help_text="User's preferred language", max_length=7),
        ),
    ]
