# Generated by Django 5.2.3 on 2025-11-07 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_language_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveluser',
            name='guest',
            field=models.BooleanField(default=False, help_text='True if this is a guest user (not fully registered)'),
        ),
        migrations.AlterField(
            model_name='reveluser',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='reveluser',
            name='totp_active',
            field=models.BooleanField(default=False),
        ),
    ]
