# Generated by Django 5.2.3 on 2025-11-10 11:54

import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_reveluser_guest_alter_reveluser_email_verified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietaryPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, help_text="Dietary preference name (e.g., 'Vegetarian', 'Vegan', 'Gluten-Free')", max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, help_text='Food or ingredient name', max_length=255)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_food_item_name_case_insensitive')],
            },
        ),
        migrations.CreateModel(
            name='DietaryRestriction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('restriction_type', models.CharField(choices=[('dislike', 'Dislike'), ('intolerant', 'Intolerant'), ('allergy', 'Allergy'), ('severe_allergy', 'Severe Allergy')], db_index=True, help_text='Severity level of the restriction', max_length=20)),
                ('notes', models.TextField(blank=True, help_text="Optional additional context (e.g., 'carry EpiPen')")),
                ('is_public', models.BooleanField(default=False, help_text='If True, visible to all event attendees (aggregated); if False, only to organizers')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_restrictions', to=settings.AUTH_USER_MODEL)),
                ('food_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_restrictions', to='accounts.fooditem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_public'], name='accounts_di_user_id_8978dc_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'food_item'), name='unique_user_food_item_restriction')],
            },
        ),
        migrations.CreateModel(
            name='UserDietaryPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('comment', models.TextField(blank=True, help_text="Optional context (e.g., 'strictly vegan, no honey')")),
                ('is_public', models.BooleanField(default=False, help_text='If True, visible to all event attendees (aggregated); if False, only to organizers')),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.dietarypreference')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietary_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_public'], name='accounts_us_user_id_5a36bd_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'preference'), name='unique_user_dietary_preference')],
            },
        ),
    ]
