# Generated by Django 5.2.3 on 2025-11-10 09:22

from django.db import migrations


def seed_dietary_preferences(apps, schema_editor):
    """Seed the DietaryPreference model with classic dietary preference options."""
    DietaryPreference = apps.get_model("accounts", "DietaryPreference")

    preferences = [
        "Vegetarian",
        "Vegan",
        "Pescatarian",
        "Gluten-Free",
        "Dairy-Free",
        "Halal",
        "Kosher",
        "Keto",
        "Paleo",
        "Low-Carb",
    ]

    for preference_name in preferences:
        DietaryPreference.objects.get_or_create(name=preference_name)


def reverse_seed_dietary_preferences(apps, schema_editor):
    """Remove seeded dietary preferences."""
    DietaryPreference = apps.get_model("accounts", "DietaryPreference")

    preferences = [
        "Vegetarian",
        "Vegan",
        "Pescatarian",
        "Gluten-Free",
        "Dairy-Free",
        "Halal",
        "Kosher",
        "Keto",
        "Paleo",
        "Low-Carb",
    ]

    DietaryPreference.objects.filter(name__in=preferences).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_dietarypreference_fooditem_dietaryrestriction_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_dietary_preferences, reverse_seed_dietary_preferences),
    ]
