# Generated by Django 5.2.3 on 2025-11-10 12:26

from django.db import migrations


def seed_common_food_items(apps, schema_editor):
    """Seed common food allergens and ingredients in English, German, and Italian."""
    FoodItem = apps.get_model("accounts", "FoodItem")

    # Common food allergens and ingredients (English, German, Italian)
    food_items = [
        # Major allergens
        ("Peanuts", "Erdnüsse", "Arachidi"),
        ("Tree nuts", "Baumnüsse", "Frutta a guscio"),
        ("Milk", "Milch", "Latte"),
        ("Eggs", "Eier", "Uova"),
        ("Fish", "Fisch", "Pesce"),
        ("Shellfish", "Schalentiere", "Crostacei"),
        ("Soy", "Soja", "Soia"),
        ("Wheat", "Weizen", "Grano"),
        ("Sesame", "Sesam", "Sesamo"),
        ("Gluten", "Gluten", "Glutine"),

        # Additional common allergens
        ("Celery", "Sellerie", "Sedano"),
        ("Mustard", "Senf", "Senape"),
        ("Lupin", "Lupine", "Lupini"),
        ("Mollusks", "Weichtiere", "Molluschi"),
        ("Sulfites", "Sulfite", "Solfiti"),

        # Common ingredients people avoid
        ("Corn", "Mais", "Mais (Granoturco)"),  # Added Italian variation to make unique
        ("Garlic", "Knoblauch", "Aglio"),
        ("Onions", "Zwiebeln", "Cipolle"),
        ("Tomatoes", "Tomaten", "Pomodori"),
        ("Strawberries", "Erdbeeren", "Fragole"),
    ]

    # Create entries for all languages
    items_to_create = []
    for en, de, it in food_items:
        items_to_create.extend([
            FoodItem(name=en),
            FoodItem(name=de),
            FoodItem(name=it),
        ])

    FoodItem.objects.bulk_create(items_to_create, ignore_conflicts=True)


def reverse_seed(apps, schema_editor):
    """Remove seeded food items."""
    FoodItem = apps.get_model("accounts", "FoodItem")

    # Delete all seeded items
    seeded_names = [
        "Peanuts", "Erdnüsse", "Arachidi",
        "Tree nuts", "Baumnüsse", "Frutta a guscio",
        "Milk", "Milch", "Latte",
        "Eggs", "Eier", "Uova",
        "Fish", "Fisch", "Pesce",
        "Shellfish", "Schalentiere", "Crostacei",
        "Soy", "Soja", "Soia",
        "Wheat", "Weizen", "Grano",
        "Sesame", "Sesam", "Sesamo",
        "Gluten", "Gluten", "Glutine",
        "Celery", "Sellerie", "Sedano",
        "Mustard", "Senf", "Senape",
        "Lupin", "Lupine", "Lupini",
        "Mollusks", "Weichtiere", "Molluschi",
        "Sulfites", "Sulfite", "Solfiti",
        "Corn", "Mais", "Mais (Granoturco)",
        "Garlic", "Knoblauch", "Aglio",
        "Onions", "Zwiebeln", "Cipolle",
        "Tomatoes", "Tomaten", "Pomodori",
        "Strawberries", "Erdbeeren", "Fragole",
    ]

    FoodItem.objects.filter(name__in=seeded_names).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_seed_dietary_preferences'),
    ]

    operations = [
        migrations.RunPython(seed_common_food_items, reverse_seed),
    ]
