# Generated by Django 5.2.8 on 2025-11-22 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_delete_accountotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerificationReminderTracking',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='verification_reminder_tracking', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_reminder_sent_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the last verification reminder email was sent', null=True)),
                ('final_warning_sent_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the final 30-day warning was sent (sent only once)', null=True)),
                ('deactivation_email_sent_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the account deactivation email was sent (sent only once)', null=True)),
            ],
            options={
                'verbose_name': 'Email Verification Reminder Tracking',
                'verbose_name_plural': 'Email Verification Reminder Tracking',
            },
        ),
    ]
