# Generated by Django

from django.db import migrations


def create_email_verification_periodic_tasks(apps, schema_editor):
    """Create periodic tasks for email verification reminder system."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Task 1: Early reminders - Every hour
    hourly_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Send early verification reminders",
        defaults={
            "task": "accounts.tasks.send_early_verification_reminders",
            "crontab": hourly_schedule,
            "enabled": True,
        },
    )

    # Task 2: Final warnings - Every hour
    PeriodicTask.objects.update_or_create(
        name="Send final verification warnings",
        defaults={
            "task": "accounts.tasks.send_final_verification_warnings",
            "crontab": hourly_schedule,
            "enabled": True,
        },
    )

    # Task 3: Deactivate unverified accounts - Daily at 2 AM
    daily_2am_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="2",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Deactivate unverified accounts",
        defaults={
            "task": "accounts.tasks.deactivate_unverified_accounts",
            "crontab": daily_2am_schedule,
            "enabled": True,
        },
    )

    # Task 4: Delete old inactive accounts - Daily at 2 AM
    PeriodicTask.objects.update_or_create(
        name="Delete old inactive accounts",
        defaults={
            "task": "accounts.tasks.delete_old_inactive_accounts",
            "crontab": daily_2am_schedule,
            "enabled": True,
        },
    )


def delete_email_verification_periodic_tasks(apps, schema_editor):
    """Remove periodic tasks for email verification reminder system."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    task_names = [
        "Send early verification reminders",
        "Send final verification warnings",
        "Deactivate unverified accounts",
        "Delete old inactive accounts",
    ]

    for task_name in task_names:
        try:
            task = PeriodicTask.objects.get(name=task_name)
            task.delete()
        except PeriodicTask.DoesNotExist:
            pass  # Task already gone, nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_emailverificationremindertracking"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_email_verification_periodic_tasks,
            reverse_code=delete_email_verification_periodic_tasks,
        ),
    ]
