# Generated by Django 5.2.8 on 2025-11-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_add_email_verification_periodic_tasks'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reveluser',
            index=models.Index(fields=['email_verified', 'is_active', 'guest', 'date_joined'], name='user_unverified_lookup_idx'),
        ),
    ]
