# Generated by Django 5.2.8 on 2025-12-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_add_unverified_user_lookup_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reveluser',
            name='pronouns',
            field=models.CharField(blank=True, help_text='Pronouns', max_length=100),
        ),
    ]
