# Generated by Django 5.2.10 on 2026-01-15 20:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_reveluser_pronouns'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address from which the impersonation was initiated', null=True)),
                ('user_agent', models.TextField(blank=True, default='', help_text='Browser/client user agent string')),
                ('token_jti', models.CharField(db_index=True, help_text='JWT ID of the impersonation request token', max_length=64, unique=True)),
                ('redeemed_at', models.DateTimeField(blank=True, db_index=True, help_text='Timestamp when the request token was exchanged for an access token', null=True)),
                ('admin_user', models.ForeignKey(help_text='The superuser who initiated the impersonation', on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_performed', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(help_text='The user being impersonated', on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Impersonation Log',
                'verbose_name_plural': 'Impersonation Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['admin_user', 'created_at'], name='accounts_im_admin_u_5a67c6_idx'), models.Index(fields=['target_user', 'created_at'], name='accounts_im_target__7feb6a_idx')],
            },
        ),
    ]
