# Generated by Django 5.2.10 on 2026-01-18 09:21

import accounts.models
import common.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_impersonation_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveluser',
            name='bio',
            field=common.fields.MarkdownField(blank=True, default='', help_text='User bio (publicly visible, supports markdown)', validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AddField(
            model_name='reveluser',
            name='profile_picture',
            field=common.fields.ProtectedImageField(blank=True, null=True, upload_to=common.fields.ProtectedUploadTo(accounts.models.profile_picture_upload_path), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp']), common.fields.validate_image_file]),
        ),
    ]
