# Generated by Django 5.2.10 on 2026-01-18 11:14

import accounts.models
import common.fields
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_reveluser_bio_reveluser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveluser',
            name='profile_picture_preview',
            field=common.fields.ProtectedImageField(blank=True, help_text='400x400 preview (auto-generated).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='reveluser',
            name='profile_picture_thumbnail',
            field=common.fields.ProtectedImageField(blank=True, help_text='150x150 thumbnail (auto-generated).', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='reveluser',
            name='profile_picture',
            field=common.fields.ProtectedImageField(blank=True, null=True, upload_to=common.fields.ProtectedUploadTo(accounts.models.profile_picture_upload_path), validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif']), common.fields.validate_image_file]),
        ),
    ]
