# Generated by Django 5.2.10 on 2026-02-01 11:02

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_reveluser_profile_picture_preview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdataexport',
            name='file',
            field=common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/user_data_exports/'),
        ),
    ]
