# Generated by Django

from django.db import migrations


def create_data_export_cleanup_task(apps, schema_editor):
    """Create periodic task to cleanup expired data export files."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Run every hour at minute 0
    hourly_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Cleanup expired data exports",
        defaults={
            "task": "accounts.tasks.cleanup_expired_data_exports",
            "crontab": hourly_schedule,
            "enabled": True,
        },
    )


def delete_data_export_cleanup_task(apps, schema_editor):
    """Remove periodic task for data export cleanup."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Cleanup expired data exports")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass  # Task already gone, nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0016_protected_file_user_data_export"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_data_export_cleanup_task,
            reverse_code=delete_data_export_cleanup_task,
        ),
    ]
