# Generated by Django 5.2.11 on 2026-02-24 22:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_add_data_export_cleanup_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalBan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('ban_type', models.CharField(choices=[('email', 'Specific Email'), ('domain', 'Email Domain'), ('telegram', 'Telegram Username')], db_index=True, max_length=20)),
                ('value', models.CharField(db_index=True, help_text='Original input value', max_length=255)),
                ('normalized_value', models.CharField(db_index=True, help_text='Normalized value for matching', max_length=255)),
                ('reason', models.TextField(blank=True, help_text='Reason for the ban')),
                ('created_by', models.ForeignKey(blank=True, help_text='Admin who created this ban', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='The user affected by this ban (linked automatically)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='global_bans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Global Ban',
                'verbose_name_plural': 'Global Bans',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('ban_type', 'normalized_value'), name='unique_global_ban')],
            },
        ),
    ]
