# Generated by Django

from django.db import migrations


def create_flush_expired_tokens_task(apps, schema_editor):
    """Create periodic task to flush expired JWT tokens."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Run every hour at minute 0
    hourly_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Flush expired JWT tokens",
        defaults={
            "task": "accounts.tasks.flush_expired_tokens",
            "crontab": hourly_schedule,
            "enabled": True,
        },
    )


def delete_flush_expired_tokens_task(apps, schema_editor):
    """Remove periodic task for flushing expired tokens."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Flush expired JWT tokens")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass  # Task already gone, nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_referralcode_referral"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_flush_expired_tokens_task,
            reverse_code=delete_flush_expired_tokens_task,
        ),
    ]
