# Generated by Django 5.2.11 on 2026-03-21 20:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_flush_expired_tokens_periodic_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralPayout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('period_start', models.DateField(db_index=True)),
                ('period_end', models.DateField(db_index=True)),
                ('gross_platform_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payout_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('status', models.CharField(choices=[('calculated', 'Calculated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], db_index=True, default='calculated', max_length=20)),
                ('stripe_transfer_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to='accounts.referral')),
            ],
            options={
                'ordering': ['-period_start'],
                'constraints': [models.UniqueConstraint(fields=('referral', 'period_start'), name='unique_referral_payout_per_period')],
            },
        ),
    ]
