# Generated by Django 5.2.11 on 2026-03-22 12:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_referralpayout'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBillingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('billing_name', models.CharField(blank=True, default='', help_text='Legal name for invoicing', max_length=255)),
                ('vat_id', models.CharField(blank=True, db_index=True, help_text='EU VAT ID with country prefix', max_length=20)),
                ('vat_country_code', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 from VAT ID prefix', max_length=2)),
                ('vat_id_validated', models.BooleanField(default=False)),
                ('vat_id_validated_at', models.DateTimeField(blank=True, null=True)),
                ('vies_request_identifier', models.CharField(blank=True, max_length=50)),
                ('billing_address', models.TextField(blank=True)),
                ('billing_country', models.CharField(blank=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2)),
                ('billing_email', models.EmailField(blank=True, help_text='Billing email (falls back to user.email in service logic)', max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Billing Profile',
                'verbose_name_plural': 'User Billing Profiles',
            },
        ),
    ]
