# Generated by Django 5.2.11 on 2026-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_billing_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveluser',
            name='stripe_account_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='reveluser',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='The Stripe Connect Account ID.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='reveluser',
            name='stripe_charges_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reveluser',
            name='stripe_details_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
