# Generated by Django 5.2.11 on 2026-03-22 21:38

import common.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_reveluser_stripe_account_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbillingprofile',
            name='self_billing_agreed',
            field=models.BooleanField(default=False, help_text='User has agreed to self-billing (Gutschrift). Required before payouts are processed.'),
        ),
        migrations.CreateModel(
            name='ReferralPayoutStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('document_type', models.CharField(choices=[('self_billing_invoice', 'Self-Billing Invoice (Gutschrift)'), ('payout_statement', 'Payout Statement')], max_length=30)),
                ('document_number', models.CharField(help_text='Sequential number (e.g., RVL-RP-2026-000001).', max_length=30, unique=True)),
                ('amount_gross', models.DecimalField(decimal_places=2, help_text='Payout amount (VAT-inclusive).', max_digits=10)),
                ('amount_net', models.DecimalField(decimal_places=2, help_text='Payout excluding VAT.', max_digits=10)),
                ('amount_vat', models.DecimalField(decimal_places=2, help_text='VAT portion.', max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, help_text='VAT rate applied.', max_digits=5)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('reverse_charge', models.BooleanField(default=False, help_text='EU cross-border B2B reverse charge.')),
                ('referrer_name', models.CharField(max_length=255)),
                ('referrer_address', models.TextField(blank=True, default='')),
                ('referrer_vat_id', models.CharField(blank=True, default='', max_length=20)),
                ('referrer_country', models.CharField(blank=True, default='', max_length=2)),
                ('platform_business_name', models.CharField(max_length=255)),
                ('platform_business_address', models.TextField()),
                ('platform_vat_id', models.CharField(max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/invoices/referral_payouts/')),
                ('payout', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='statement', to='accounts.referralpayout')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
