# Generated by Django

from django.db import migrations


def create_process_referral_payouts_task(apps, schema_editor):
    """Create periodic task to process referral payouts via Stripe."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Run on 1st of month at 06:30 UTC (30 min after calculation task)
    monthly_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="30",
        hour="6",
        day_of_week="*",
        day_of_month="1",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Process referral payouts (Stripe transfers)",
        defaults={
            "task": "accounts.process_referral_payouts",
            "crontab": monthly_schedule,
            "enabled": True,
        },
    )


def delete_process_referral_payouts_task(apps, schema_editor):
    """Remove periodic task for referral payout processing."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Process referral payouts (Stripe transfers)")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0024_userbillingprofile_self_billing_agreed_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_process_referral_payouts_task,
            reverse_code=delete_process_referral_payouts_task,
        ),
    ]
