# Generated by Django 5.2.11 on 2026-03-23 12:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_process_referral_payouts_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpayout',
            name='rolled_over_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount carried forward from prior below-threshold periods.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='payout_amount',
            field=models.DecimalField(decimal_places=2, help_text='net_platform_fees * revenue_share_percent / 100 + rolled_over_amount', max_digits=10),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='status',
            field=models.CharField(choices=[('calculated', 'Calculated'), ('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('rolled_over', 'Rolled Over')], db_index=True, default='calculated', max_length=20),
        ),
    ]
