# Generated by Django 5.2.11 on 2026-03-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_add_process_referral_payouts_periodic_task'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='referralpayoutstatement',
            name='idx_stmt_payout_type',
        ),
    ]
