# Generated by Django 5.2.15 on 2026-06-14 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_referralpayout_rolled_over_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reveluser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('it', 'Italiano'), ('fr', 'Français')], db_index=True, default='en', help_text="User's preferred language", max_length=7),
        ),
    ]
