# Generated by Django 5.2.15 on 2026-06-24 11:03

import typing as t

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Coalesce


def backfill_email_sent_at(apps: t.Any, schema_editor: t.Any) -> None:
    """Mark pre-existing statements as already delivered (issue #616).

    Without this, every statement created before the field existed has
    ``email_sent_at`` null, so the widened recovery sweep would treat every
    already-emailed payout statement as undelivered and re-send it. Backfill to
    ``issued_at`` (falling back to ``created_at``) so the sweep only targets
    genuinely undelivered records going forward.
    """
    ReferralPayoutStatement = apps.get_model("accounts", "ReferralPayoutStatement")
    ReferralPayoutStatement.objects.filter(email_sent_at__isnull=True).update(
        email_sent_at=Coalesce(F("issued_at"), F("created_at"))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_reveluser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpayoutstatement',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the document was successfully emailed to its recipient.', null=True),
        ),
        migrations.RunPython(backfill_email_sent_at, migrations.RunPython.noop),
    ]
