# Generated by Django 5.2.15 on 2026-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_alter_reveluser_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpayoutstatement',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the document was successfully emailed to its recipient.', null=True),
        ),
    ]
