# Generated by Django 5.2.15 on 2026-06-25 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_referralpayoutstatement_email_sent_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='referralpayoutstatement',
            name='email_delivery_error',
            field=models.CharField(blank=True, choices=[('no_recipient', 'No resolvable recipient'), ('org_deleted', 'Organization deleted')], help_text='Why the document is permanently undeliverable.', max_length=32),
        ),
        migrations.AddField(
            model_name='referralpayoutstatement',
            name='email_delivery_failed_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the document was found permanently undeliverable (no recipient / org gone).', null=True),
        ),
    ]
