# Generated by Django 5.2.16 on 2026-07-28 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_referralpayoutstatement_email_delivery_error_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referred_user',
            field=models.OneToOneField(blank=True, help_text="Nulled when the referred user deletes their account; the referrer's payout history survives.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='referralpayout',
            name='referral',
            field=models.ForeignKey(blank=True, help_text='Nulled when the referrer deletes their account; PAID payouts and their statements are retained.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts', to='accounts.referral'),
        ),
    ]
