# Generated by Django 5.2.16 on 2026-07-29 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_referral_referred_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reveluser',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'Deutsch'), ('it', 'Italiano'), ('fr', 'Français'), ('es', 'Español'), ('pt', 'Português')], db_index=True, default='en', help_text="User's preferred language", max_length=7),
        ),
    ]
