# Generated by Django 5.2.17 on 2026-09-02 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0031_alter_reveluser_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("provider", models.CharField(max_length=64)),
                ("subject", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, help_text="Email claim at link time (informational).", max_length=254
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider", "subject"), name="uniq_external_identity_provider_subject"
                    ),
                    models.UniqueConstraint(fields=("user", "provider"), name="uniq_external_identity_user_provider"),
                ],
            },
        ),
    ]
