# Generated by Django 5.2.17 on 2026-09-16 13:09

import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_backfill_external_identity_from_google_sso'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(help_text='Applicant email, lowercased', max_length=254)),
                ('normalized_email', models.CharField(db_index=True, editable=False, help_text='Normalized for matching (same rules as GlobalBan)', max_length=255)),
                ('code', models.CharField(help_text='Desired referral code', max_length=20, validators=[django.core.validators.RegexValidator(message='Referral codes use 3 to 20 letters, digits, dashes or underscores.', regex='^[A-Za-z0-9_-]{3,20}$')])),
                ('revenue_share_percent', models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='Share percent the referral code will carry once approved', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('note', models.TextField(blank=True, help_text="Applicant's note (plain text). Required for public applications.")),
                ('admin_note', models.TextField(blank=True, help_text='Included in the rejection email, or in the invite email for invites, when present.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('blocked', 'Blocked')], db_index=True, default='pending', max_length=20)),
                ('source', models.CharField(choices=[('application', 'Application'), ('invite', 'Invite')], default='application', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='referralcode',
            name='revenue_share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Overrides settings.DEFAULT_REFERRAL_SHARE_PERCENT for referrals this code produces.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='referralcode',
            name='code',
            field=models.CharField(help_text='Referral code (case-insensitive, immutable)', max_length=20, validators=[django.core.validators.RegexValidator(message='Referral codes use 3 to 20 letters, digits, dashes or underscores.', regex='^[A-Za-z0-9_-]{3,20}$')]),
        ),
        migrations.AddConstraint(
            model_name='referralcode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_referral_code_ci'),
        ),
        migrations.AddField(
            model_name='referralapplication',
            name='decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralapplication',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Set once the applicant is enrolled (a ReferralCode exists)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referral_applications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='referralapplication',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('normalized_email',), name='unique_pending_referral_application_per_email'),
        ),
    ]
