# Generated by Django 5.2.17 on 2026-09-29 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_referral_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='reveluser',
            name='credentials_changed_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Last password reset; single-use links issued before it are rejected.', null=True),
        ),
    ]
