# Generated by Django 5.2.3 on 2025-08-04 12:08

from django.db import migrations


def create_cleanup_expired_payments_task(apps, schema_editor):
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="*/5",
        hour="*",  # Every 12 hours: 00:00, 12:00
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Cleanup expired payments",
        defaults={
            "task": "events.cleanup_expired_payments",
            "crontab": schedule,
            "enabled": True,
        },
    )


def delete_cleanup_expired_payments_task(apps, schema_editor):
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Cleanup expired payments")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass  # Task already gone, nothing to do


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(create_cleanup_expired_payments_task, reverse_code=delete_cleanup_expired_payments_task),
    ]
