# Generated by Django 5.2.3 on 2025-10-16 17:37

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_add_cleanup_expired_payments_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalresource',
            name='description',
            field=common.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='additionalresource',
            name='text',
            field=common.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=common.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='invitation_message',
            field=common.fields.MarkdownField(blank=True, help_text='Invitation message to override the one automatically generated using name and description.', null=True),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='description',
            field=common.fields.MarkdownField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='description',
            field=common.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='potluckitem',
            name='note',
            field=common.fields.MarkdownField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='description',
            field=common.fields.MarkdownField(blank=True, null=True),
        ),
    ]
