# Generated by Django 5.2.3 on 2025-10-21 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_additionalresource_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationquestionnaire',
            name='max_submission_age',
            field=models.DurationField(blank=True, db_index=True, null=True),
        ),
    ]
