# Generated by Django 5.2.3 on 2025-10-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_organizationquestionnaire_max_submission_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accept_invitation_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='accept_membership_requests',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='contact_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, help_text='Stripe PaymentIntent ID for refund processing', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='OrganizationSettings',
        ),
    ]
