# Generated by Django 5.2.3 on 2025-10-29 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_payment_ticket_alter_payment_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtoken',
            name='invitation_tier',
        ),
        migrations.AddField(
            model_name='eventtoken',
            name='ticket_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.tickettier'),
        ),
        migrations.AddIndex(
            model_name='eventtoken',
            index=models.Index(fields=['event', 'expires_at'], name='eventtoken_event_expires'),
        ),
        migrations.AddIndex(
            model_name='eventtoken',
            index=models.Index(fields=['event', '-created_at'], name='eventtoken_event_created'),
        ),
        migrations.AddIndex(
            model_name='organizationtoken',
            index=models.Index(fields=['organization', 'expires_at'], name='orgtoken_org_expires'),
        ),
        migrations.AddIndex(
            model_name='organizationtoken',
            index=models.Index(fields=['organization', '-created_at'], name='orgtoken_org_created'),
        ),
    ]
