# Generated by Django 5.2.3 on 2025-10-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_eventtoken_invitation_tier_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalresource',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventinvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='eventtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='organizationmember',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organizationquestionnaire',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organizationstaff',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='organizationtoken',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='pendingeventinvitation',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
    ]
