# Generated by Django 5.2.3 on 2025-10-31 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_additionalresource_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickettier',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('at_the_door', 'At The Door'), ('free', 'Free')], db_index=True, default='offline', max_length=20),
        ),
    ]
