# Generated by Django 5.2.3 on 2025-11-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_tickettier_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='can_attend_without_login',
            field=models.BooleanField(default=True, help_text='Allow users to RSVP or purchase tickets without creating an account'),
        ),
    ]
