# Generated by Django 5.2.3 on 2025-11-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_event_can_attend_without_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usereventseriespreferences',
            name='event_series',
        ),
        migrations.RemoveField(
            model_name='usereventseriespreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userorganizationpreferences',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='userorganizationpreferences',
            name='user',
        ),
        migrations.RemoveField(
            model_name='generaluserpreferences',
            name='event_reminders',
        ),
        migrations.RemoveField(
            model_name='generaluserpreferences',
            name='silence_all_notifications',
        ),
        migrations.DeleteModel(
            name='UserEventPreferences',
        ),
        migrations.DeleteModel(
            name='UserEventSeriesPreferences',
        ),
        migrations.DeleteModel(
            name='UserOrganizationPreferences',
        ),
    ]
