# Generated by Django 5.2.3 on 2025-11-18 21:59

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_subscription_preferences'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmember',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('cancelled', 'Cancelled'), ('banned', 'Banned')], db_index=True, default='active', max_length=255),
        ),
        migrations.CreateModel(
            name='MembershipTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('description', common.fields.MarkdownField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tiers', to='events.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='organizationmember',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='events.membershiptier'),
        ),
        migrations.AddField(
            model_name='organizationtoken',
            name='membership_tier',
            field=models.ForeignKey(blank=True, help_text='Membership tier to assign when claiming this token', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='events.membershiptier'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='restricted_to_membership_tiers',
            field=models.ManyToManyField(blank=True, help_text='If set, only members of these tiers can purchase this ticket.', related_name='restricted_ticket_tiers', to='events.membershiptier'),
        ),
        migrations.AddIndex(
            model_name='organizationmember',
            index=models.Index(fields=['user', 'status'], name='events_orga_user_id_e0d2e9_idx'),
        ),
        migrations.AddConstraint(
            model_name='organizationmember',
            constraint=models.UniqueConstraint(fields=('organization', 'user'), name='unique_organization_member_user'),
        ),
        migrations.AddConstraint(
            model_name='membershiptier',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_organization_tier_name'),
        ),
    ]
