# Generated by Django 5.2.8 on 2025-11-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_create_default_tiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventseries',
            options={'ordering': ('organization__name', 'name')},
        ),
        migrations.RemoveField(
            model_name='event',
            name='free_for_members',
        ),
        migrations.RemoveField(
            model_name='event',
            name='free_for_staff',
        ),
    ]
