# Generated by Django 5.2.8 on 2025-11-20 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_create_default_tiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='free_for_members',
        ),
        migrations.RemoveField(
            model_name='event',
            name='free_for_staff',
        ),
    ]
