# Generated by Django 5.2.8 on 2025-11-26 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_alter_eventseries_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='stripe_account_email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
    ]
