# Generated by Django 5.2.8 on 2025-11-28 17:57

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_populate_stripe_account_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('draft', 'Draft'), ('cancelled', 'Cancelled')], default='draft', max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='platform_fee_fixed',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.25'), help_text='The fixed platform fee for this organization.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='platform_fee_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='The percentage platform fee Revel takes on ticket sales for this organization.', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
