# Generated by Django 5.2.8 on 2025-11-28 19:33

from django.db import migrations


def migrate_deleted_to_cancelled(apps, schema_editor):
    """Migrate events with status 'deleted' to 'cancelled'."""
    Event = apps.get_model("events", "Event")

    # Update all events with status='deleted' to status='cancelled'
    updated_count = Event.objects.filter(status="deleted").update(status="cancelled")


def reverse_migrate_cancelled_to_deleted(apps, schema_editor):
    """Reverse migration: Note that this cannot reliably restore 'deleted' status.

    This reverse operation is provided for completeness but should not be used
    in production as it cannot distinguish between events that were originally
    'deleted' vs those that were legitimately 'cancelled'.
    """
    # We don't reverse this migration since 'deleted' is no longer a valid status
    # and we can't distinguish which 'cancelled' events were originally 'deleted'
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_status_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_deleted_to_cancelled,
            reverse_code=reverse_migrate_cancelled_to_deleted,
        ),
    ]
