# Generated by Django 5.2.8 on 2025-11-29 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_migrate_deleted_to_cancelled'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='event',
            name='unique_organization_name',
        ),
    ]
