# Generated by Django 5.2.8 on 2025-11-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_drop_unique_organization_name_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalresource',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only'), ('attendees-only', 'Attendees Only')], db_index=True, default='private', max_length=20),
        ),
    ]
