# Generated by Django 5.2.8 on 2025-11-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_add_attendees_only_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only'), ('attendees-only', 'Attendees Only')], default='public', help_text='Controls who can see the event address. Uses same rules as resource visibility.', max_length=20),
        ),
    ]
