# Generated by Django 5.2.8 on 2025-12-07 13:24

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_add_address_visibility'),
        ('geo', '0003_add_download_ip2location_periodic_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VenueSeat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('label', models.CharField(db_index=True, max_length=50)),
                ('row', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('number', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('position', models.JSONField(blank=True, help_text='Seat position for FE rendering (pixel-based or relative coordinate).', null=True)),
                ('is_accessible', models.BooleanField(db_index=True, default=False)),
                ('is_obstructed_view', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['sector', 'row', 'number', 'label'],
            },
        ),
        migrations.AddField(
            model_name='tickettier',
            name='seat_assignment_mode',
            field=models.CharField(choices=[('none', 'No seat assignment (GA/standing)'), ('random', 'Random assignment at purchase'), ('user_choice', 'User chooses seat')], db_index=True, default='none', help_text='How seats are assigned for tickets in this tier.', max_length=20),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.city')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='events.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Optional venue for this event.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.venue'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.venue'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='venue',
            field=models.ForeignKey(blank=True, help_text='Venue for this tier. Must match event venue if event has one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_tiers', to='events.venue'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.venueseat'),
        ),
        migrations.CreateModel(
            name='VenueSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('code', models.CharField(blank=True, max_length=30, null=True)),
                ('shape', models.JSONField(blank=True, help_text='Arbitrary polygon for FE rendering (list of points: [[x,y],...]).', null=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='events.venue')),
            ],
            options={
                'ordering': ['venue', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='venueseat',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='events.venuesector'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.venuesector'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='sector',
            field=models.ForeignKey(blank=True, help_text='Specific sector for this tier.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_tiers', to='events.venuesector'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('seat__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('event', 'seat'), name='unique_ticket_event_seat'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['organization', 'name'], name='events_venu_organiz_50829e_idx'),
        ),
        migrations.AddConstraint(
            model_name='venue',
            constraint=models.UniqueConstraint(fields=('organization', 'slug'), name='unique_organization_venue_slug'),
        ),
        migrations.AddIndex(
            model_name='venuesector',
            index=models.Index(fields=['venue', 'display_order'], name='events_venu_venue_i_80684c_idx'),
        ),
        migrations.AddIndex(
            model_name='venuesector',
            index=models.Index(fields=['venue', 'name'], name='events_venu_venue_i_65c220_idx'),
        ),
        migrations.AddConstraint(
            model_name='venuesector',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_venue_sector_name'),
        ),
        migrations.AddIndex(
            model_name='venueseat',
            index=models.Index(fields=['sector', 'row', 'number'], name='events_venu_sector__33fcd5_idx'),
        ),
        migrations.AddIndex(
            model_name='venueseat',
            index=models.Index(fields=['sector', 'label'], name='events_venu_sector__c082ab_idx'),
        ),
        migrations.AddIndex(
            model_name='venueseat',
            index=models.Index(fields=['sector', 'is_active'], name='events_venu_sector__65c9a0_idx'),
        ),
        migrations.AddConstraint(
            model_name='venueseat',
            constraint=models.UniqueConstraint(fields=('sector', 'label'), name='unique_sector_seat_label'),
        ),
    ]
