# Generated by Django 5.2.8 on 2025-12-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_venueseat_tickettier_seat_assignment_mode_venue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venuesector',
            name='metadata',
            field=models.JSONField(blank=True, default=None, help_text='Arbitrary JSON metadata for frontend rendering (e.g., aisle positions).', null=True),
        ),
    ]
