# Generated by Django 5.2.8 on 2025-12-09 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_add_venuesector_metadata'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='ticket',
            name='unique_ticket_event_user_tier',
        ),
        migrations.AddField(
            model_name='event',
            name='max_tickets_per_user',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Maximum tickets a user can purchase for this event. Null = unlimited.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Name of the ticket holder (may differ from purchasing user).', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='max_tickets_per_user',
            field=models.PositiveIntegerField(blank=True, help_text="Override event's max_tickets_per_user for this tier. Null = inherit from event.", null=True),
        ),
    ]
