# Generated by Django 5.2.8 on 2025-12-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_populate_guest_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='guest_name',
            field=models.CharField(help_text='Name of the ticket holder (may differ from purchasing user).', max_length=255),
        ),
    ]
