# Generated by Django 5.2.8 on 2025-12-12 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_payment_batch_session_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Informational only. Not enforced during ticket sales.', null=True),
        ),
        migrations.AlterField(
            model_name='venuesector',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Informational only. Actual capacity enforced by materialized seats.', null=True),
        ),
    ]
