# Generated by Django 5.2.8 on 2025-12-12 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_alter_venue_capacity_alter_venuesector_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='bluesky_url',
            field=models.URLField(blank=True, verbose_name='Bluesky'),
        ),
        migrations.AddField(
            model_name='organization',
            name='facebook_url',
            field=models.URLField(blank=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='organization',
            name='instagram_url',
            field=models.URLField(blank=True, verbose_name='Instagram'),
        ),
        migrations.AddField(
            model_name='organization',
            name='telegram_url',
            field=models.URLField(blank=True, verbose_name='Telegram'),
        ),
    ]
