# Generated by Django 5.2.8 on 2025-12-28 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_organization_bluesky_url_organization_facebook_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationquestionnaire',
            name='members_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
