# Generated by Django 5.2.8 on 2025-12-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_add_members_exempt_to_organizationquestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venueseat',
            name='is_accessible',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='venueseat',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
