# Generated by Django 5.2.8 on 2026-01-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_alter_venueseat_is_accessible_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationquestionnaire',
            name='max_submission_age',
            field=models.DurationField(blank=True, db_index=True, help_text='How long a completed submission remains valid before user must retake.', null=True),
        ),
    ]
