# Generated by Django 5.2.8 on 2026-01-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0032_alter_organizationquestionnaire_max_submission_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='apply_before',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Deadline for submitting invitation requests or questionnaires', null=True),
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='waives_apply_deadline',
            field=models.BooleanField(default=False, help_text='Waives application deadline check for this user'),
        ),
        migrations.AddField(
            model_name='pendingeventinvitation',
            name='waives_apply_deadline',
            field=models.BooleanField(default=False, help_text='Waives application deadline check for this user'),
        ),
    ]
