# Generated by Django 5.2.8 on 2026-01-12 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0033_add_apply_before_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location_maps_embed',
            field=models.URLField(blank=True, help_text='Embed URL for iframe src (e.g., https://www.google.com/maps/embed?pb=...)', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location_maps_url',
            field=models.URLField(blank=True, help_text='Shareable link to Google Maps (e.g., https://goo.gl/maps/...)', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_maps_embed',
            field=models.URLField(blank=True, help_text='Embed URL for iframe src (e.g., https://www.google.com/maps/embed?pb=...)', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='location_maps_url',
            field=models.URLField(blank=True, help_text='Shareable link to Google Maps (e.g., https://goo.gl/maps/...)', null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='location_maps_embed',
            field=models.URLField(blank=True, help_text='Embed URL for iframe src (e.g., https://www.google.com/maps/embed?pb=...)', max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='location_maps_url',
            field=models.URLField(blank=True, help_text='Shareable link to Google Maps (e.g., https://goo.gl/maps/...)', null=True),
        ),
    ]
