# Generated by Django 5.2.8 on 2026-01-13 11:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0034_add_location_maps_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('telegram_username', models.CharField(blank=True, db_index=True, help_text='Telegram username without @ prefix', max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, db_index=True, help_text='Phone number in E.164 format', max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=150, null=True)),
                ('last_name', models.CharField(blank=True, max_length=150, null=True)),
                ('preferred_name', models.CharField(blank=True, max_length=150, null=True)),
                ('reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='events.organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blacklist Entry',
                'verbose_name_plural': 'Blacklist Entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WhitelistRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('message', models.TextField(blank=True, help_text="User's explanation for why they should be whitelisted")),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_blacklist_entries', models.ManyToManyField(help_text='The blacklist entries that triggered this request', related_name='triggered_whitelist_requests', to='events.blacklist')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_requests', to='events.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='whitelist_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Whitelist Request',
                'verbose_name_plural': 'Whitelist Requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['organization', 'user'], name='blacklist_org_user'),
        ),
        migrations.AddIndex(
            model_name='blacklist',
            index=models.Index(fields=['organization', 'email'], name='blacklist_org_email'),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('organization', 'user'), name='unique_blacklist_user_per_org'),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('user__isnull', True)), fields=('organization', 'email'), name='unique_blacklist_email_per_org'),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(condition=models.Q(('telegram_username__isnull', False), ('user__isnull', True)), fields=('organization', 'telegram_username'), name='unique_blacklist_telegram_per_org'),
        ),
        migrations.AddConstraint(
            model_name='blacklist',
            constraint=models.UniqueConstraint(condition=models.Q(('phone_number__isnull', False), ('user__isnull', True)), fields=('organization', 'phone_number'), name='unique_blacklist_phone_per_org'),
        ),
        migrations.AddConstraint(
            model_name='whitelistrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'user'), name='unique_pending_whitelist_request_per_org'),
        ),
    ]
