# Generated by Django 5.2.10 on 2026-01-16 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0036_add_event_feedback_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeriesFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notify_new_events', models.BooleanField(default=True, help_text='Receive notifications when new events are added to the series')),
                ('is_public', models.BooleanField(default=False, help_text="Whether this follow is publicly visible on the user's profile")),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Archived follows are hidden but preserved for history')),
                ('event_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='events.eventseries')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_series_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_series', 'is_archived'], name='events_even_event_s_162d41_idx'), models.Index(fields=['user', 'is_archived'], name='events_even_user_id_6d4592_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'event_series'), name='unique_user_event_series_follow')],
            },
        ),
        migrations.CreateModel(
            name='OrganizationFollow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('notify_new_events', models.BooleanField(default=True, help_text='Receive notifications when the organization creates new events')),
                ('notify_announcements', models.BooleanField(default=True, help_text='Receive notifications when the organization makes announcements')),
                ('is_public', models.BooleanField(default=False, help_text="Whether this follow is publicly visible on the user's profile")),
                ('is_archived', models.BooleanField(db_index=True, default=False, help_text='Archived follows are hidden but preserved for history')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='events.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organization_follows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_archived'], name='events_orga_organiz_1693ca_idx'), models.Index(fields=['user', 'is_archived'], name='events_orga_user_id_9a8a54_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'organization'), name='unique_user_organization_follow')],
            },
        ),
    ]
