# Generated by Django 5.2.10 on 2026-01-16 19:39

import os
import shutil

import common.fields
from django.conf import settings
from django.db import migrations


def move_files_to_protected(apps, schema_editor):
    """Move AdditionalResource files from file/ to protected/file/."""
    AdditionalResource = apps.get_model("events", "AdditionalResource")
    media_root = settings.MEDIA_ROOT

    for resource in AdditionalResource.objects.exclude(file="").exclude(file__isnull=True):
        old_path = resource.file.name
        # Skip if already in protected/
        if old_path.startswith("protected/"):
            continue

        new_path = f"protected/{old_path}"

        # Move file on disk
        old_full_path = os.path.join(media_root, old_path)
        new_full_path = os.path.join(media_root, new_path)

        if os.path.exists(old_full_path):
            # Create directory if needed
            os.makedirs(os.path.dirname(new_full_path), exist_ok=True)
            shutil.move(old_full_path, new_full_path)

        # Update database path
        resource.file.name = new_path
        resource.save(update_fields=["file"])


def move_files_from_protected(apps, schema_editor):
    """Reverse: Move files from protected/file/ back to file/."""
    AdditionalResource = apps.get_model("events", "AdditionalResource")
    media_root = settings.MEDIA_ROOT

    for resource in AdditionalResource.objects.exclude(file="").exclude(file__isnull=True):
        old_path = resource.file.name
        # Only process files in protected/file/
        if not old_path.startswith("protected/file/"):
            continue

        new_path = old_path[len("protected/"):]  # Remove "protected/" prefix

        # Move file on disk
        old_full_path = os.path.join(media_root, old_path)
        new_full_path = os.path.join(media_root, new_path)

        if os.path.exists(old_full_path):
            os.makedirs(os.path.dirname(new_full_path), exist_ok=True)
            shutil.move(old_full_path, new_full_path)

        # Update database path
        resource.file.name = new_path
        resource.save(update_fields=["file"])


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0038_create_follows_for_existing_members'),
    ]

    operations = [
        # First move the files
        migrations.RunPython(move_files_to_protected, move_files_from_protected),
        # Then alter the field
        migrations.AlterField(
            model_name='additionalresource',
            name='file',
            field=common.fields.ProtectedFileField(blank=True, null=True, upload_to='file'),
        ),
    ]
