# Generated by Django 5.2.10 on 2026-01-18 11:14

import common.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0039_protected_file_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cover_art_social',
            field=models.ImageField(blank=True, help_text='1200x630 social preview for cover art (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='cover_art_thumbnail',
            field=models.ImageField(blank=True, help_text='150x150 cover art thumbnail (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='event',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, help_text='150x150 logo thumbnail (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='cover_art_social',
            field=models.ImageField(blank=True, help_text='1200x630 social preview for cover art (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='cover_art_thumbnail',
            field=models.ImageField(blank=True, help_text='150x150 cover art thumbnail (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, help_text='150x150 logo thumbnail (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='cover_art_social',
            field=models.ImageField(blank=True, help_text='1200x630 social preview for cover art (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='cover_art_thumbnail',
            field=models.ImageField(blank=True, help_text='150x150 cover art thumbnail (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_thumbnail',
            field=models.ImageField(blank=True, help_text='150x150 logo thumbnail (auto-generated).', max_length=255, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='event',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='cover-art', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif']), common.fields.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='event',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif']), common.fields.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='cover-art', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif']), common.fields.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='eventseries',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif']), common.fields.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='cover-art', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif']), common.fields.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif']), common.fields.validate_image_file]),
        ),
    ]
