# Generated by Django 5.2.10 on 2026-01-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0040_event_cover_art_social_event_cover_art_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requires_full_profile',
            field=models.BooleanField(default=False, help_text='Whether this event requires full profile information (profile pic, name, pronouns)'),
        ),
    ]
