# Generated by Django 5.2.10 on 2026-01-20 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0042_rename_event_questionnaire_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid per ticket for PWYC offline/at_the_door purchases. Null for online payments (stored in Payment.amount) or fixed-price tiers (use tier.price).', max_digits=10, null=True),
        ),
    ]
