# Generated by Django 5.2.10 on 2026-01-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0043_ticket_price_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Combined with Event.max_attendees to determine effective capacity (min of both). 0/null = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='venuesector',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Hard capacity limit for GA tiers. Enforced during ticket sales. For seated tiers, capacity is enforced by seat count.', null=True),
        ),
    ]
