# Generated by Django 5.2.10 on 2026-01-24 10:38

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0044_alter_venue_capacity_alter_venuesector_capacity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('target_all_members', models.BooleanField(default=False, help_text='Target all active organization members')),
                ('target_staff_only', models.BooleanField(default=False, help_text='Target only organization staff members')),
                ('title', models.CharField(max_length=150)),
                ('body', common.fields.MarkdownField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent')], db_index=True, default='draft', max_length=20)),
                ('past_visibility', models.BooleanField(default=True, help_text='Allow new attendees/members to see this announcement after it was sent')),
                ('sent_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_announcements', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='events.organization')),
                ('target_tiers', models.ManyToManyField(blank=True, help_text='Target members of specific membership tiers', related_name='targeted_announcements', to='events.membershiptier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='events_anno_organiz_5a7069_idx'), models.Index(fields=['event', 'status'], name='events_anno_event_i_9a2907_idx')],
            },
        ),
    ]
