# Generated by Django 5.2.11 on 2026-02-05 10:08

from django.db import migrations


def migrate_at_the_door_tickets_to_active(apps, schema_editor):
    """Migrate PENDING AT_THE_DOOR tickets to ACTIVE for future events.

    AT_THE_DOOR represents a commitment to attend (pay at arrival), so tickets
    should be ACTIVE and count toward attendee_count. Previously they were
    created as PENDING (reusing the OFFLINE checkout path).

    Only migrates tickets for future events to avoid changing historical data.
    """
    Ticket = apps.get_model("events", "Ticket")
    from django.utils import timezone

    Ticket.objects.filter(
        status="pending",
        tier__payment_method="at_the_door",
        event__start__gt=timezone.now(),
    ).update(status="active")


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0045_announcement"),
    ]

    operations = [
        migrations.RunPython(
            migrate_at_the_door_tickets_to_active,
            reverse_code=migrations.RunPython.noop,
            elidable=True,
        ),
    ]
