# Generated by Django 5.2.11 on 2026-02-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0046_migrate_at_the_door_tickets_to_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationquestionnaire',
            name='per_event',
            field=models.BooleanField(default=False, help_text='When True, users must complete the questionnaire separately for each event.'),
        ),
    ]
