# Generated by Django 5.2.11 on 2026-02-13 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0047_organizationquestionnaire_per_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tickettier',
            options={'ordering': ['event', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='tickettier',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='tickettier',
            index=models.Index(fields=['event', 'display_order'], name='events_tick_event_i_31ce39_idx'),
        ),
    ]
