# Generated by Django 5.2.11 on 2026-02-16 18:07

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0048_alter_tickettier_options_tickettier_display_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='file_content_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pdf_file',
            field=common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/tickets/pdf/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='pkpass_file',
            field=common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/tickets/pkpass/'),
        ),
    ]
