# Generated by Django

from django.db import migrations


def create_ticket_file_cache_cleanup_task(apps, schema_editor):
    """Create periodic task to clean up cached ticket files for past events."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Run daily at 3:00 AM UTC
    daily_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="3",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Cleanup cached ticket files for past events",
        defaults={
            "task": "events.cleanup_ticket_file_cache",
            "crontab": daily_schedule,
            "enabled": True,
        },
    )


def delete_ticket_file_cache_cleanup_task(apps, schema_editor):
    """Remove periodic task for ticket file cache cleanup."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Cleanup cached ticket files for past events")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0049_ticket_file_cache_fields"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_ticket_file_cache_cleanup_task,
            reverse_code=delete_ticket_file_cache_cleanup_task,
        ),
    ]
