# Generated by Django 5.2.11 on 2026-03-04 17:08

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0050_add_ticket_file_cache_cleanup_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount discounted from the original tier price.', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=64)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('fixed_amount', 'Fixed Amount')], db_index=True, max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(blank=True, help_text='Required for FIXED_AMOUNT discount type. ISO 4217 currency code.', max_length=3, null=True)),
                ('valid_from', models.DateTimeField(blank=True, help_text='When the discount code becomes valid. None = immediately valid.', null=True)),
                ('valid_until', models.DateTimeField(blank=True, help_text='When the discount code expires. None = no expiry.', null=True)),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum total uses. None = unlimited.', null=True)),
                ('max_uses_per_user', models.PositiveIntegerField(default=1, help_text='Maximum uses per user.')),
                ('times_used', models.PositiveIntegerField(default=0, help_text='Number of times this code has been used. Atomically incremented via F().')),
                ('min_purchase_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum purchase amount (price x quantity) required to use this code.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Manual kill switch to deactivate the discount code.')),
                ('events', models.ManyToManyField(blank=True, related_name='discount_codes', to='events.event')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_codes', to='events.organization')),
                ('series', models.ManyToManyField(blank=True, related_name='discount_codes', to='events.eventseries')),
                ('tiers', models.ManyToManyField(blank=True, related_name='discount_codes', to='events.tickettier')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='discount_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.discountcode'),
        ),
        migrations.AddConstraint(
            model_name='discountcode',
            constraint=models.UniqueConstraint(fields=('organization', 'code'), name='unique_org_discount_code'),
        ),
    ]
