# Generated by Django 5.2.11 on 2026-03-10 19:08

import common.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0051_ticket_discount_amount_discountcode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='billing_address',
            field=models.TextField(blank=True, default='', help_text='Organization billing address for invoicing.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, default='', help_text='Email address for invoice delivery. Falls back to contact_email if empty.', max_length=254),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_country_code',
            field=models.CharField(blank=True, default='', help_text='ISO 3166-1 alpha-2 country code for VAT purposes.', max_length=2),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='EU VAT identification number including country prefix (e.g., IT12345678901).', max_length=20),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_id_validated',
            field=models.BooleanField(default=False, help_text='Whether the VAT ID has been validated via VIES.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_id_validated_at',
            field=models.DateTimeField(blank=True, help_text='When the VAT ID was last validated via VIES.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Default VAT rate for ticket sales (e.g., 22.00 for 22%).', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='organization',
            name='vies_request_identifier',
            field=models.CharField(blank=True, default='', help_text='VIES request identifier from the last validation (compliance audit trail).', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='net_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Ticket price excluding VAT.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee_net',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee excluding VAT.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee_reverse_charge',
            field=models.BooleanField(default=False, help_text='Whether reverse charge applies to the platform fee (EU B2B cross-border).'),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT portion of the platform fee.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='platform_fee_vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee VAT rate snapshot.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vat_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT portion of the ticket price.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT rate snapshot at purchase time.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="VAT rate override for this tier. If null, uses organization's default vat_rate.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.CreateModel(
            name='PlatformFeeInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('invoice_number', models.CharField(help_text='Sequential invoice number (e.g., RVL-2024-001234).', max_length=30, unique=True)),
                ('period_start', models.DateField(help_text='First day of the invoiced period.')),
                ('period_end', models.DateField(help_text='Last day of the invoiced period.')),
                ('fee_gross', models.DecimalField(decimal_places=2, help_text='Total fee (VAT-inclusive).', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_net', models.DecimalField(decimal_places=2, help_text='Fee excluding VAT.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_vat', models.DecimalField(decimal_places=2, help_text='VAT portion of the fee.', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('fee_vat_rate', models.DecimalField(decimal_places=2, help_text='VAT rate applied to this invoice.', max_digits=5)),
                ('currency', models.CharField(default='EUR', help_text='ISO 4217 currency code.', max_length=3)),
                ('reverse_charge', models.BooleanField(default=False, help_text='Whether reverse charge applies (EU B2B cross-border).')),
                ('org_name', models.CharField(max_length=255)),
                ('org_vat_id', models.CharField(blank=True, default='', max_length=20)),
                ('org_vat_country', models.CharField(blank=True, default='', max_length=2)),
                ('org_address', models.TextField(blank=True, default='')),
                ('platform_business_name', models.CharField(max_length=255)),
                ('platform_business_address', models.TextField()),
                ('platform_vat_id', models.CharField(max_length=20)),
                ('total_tickets', models.PositiveIntegerField(default=0, help_text='Number of tickets sold in this period.')),
                ('total_ticket_revenue', models.DecimalField(decimal_places=2, default=0, help_text='Total ticket revenue in this period.', max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, help_text='When the invoice was issued.', null=True)),
                ('pdf_file', common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/invoices/platform_fee/')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_fee_invoices', to='events.organization')),
            ],
            options={
                'ordering': ['-period_start', 'org_name'],
            },
        ),
        migrations.CreateModel(
            name='PlatformFeeCreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('credit_note_number', models.CharField(help_text='Sequential credit note number (e.g., RVL-CN-2024-001234).', max_length=30, unique=True)),
                ('fee_gross', models.DecimalField(decimal_places=2, help_text='Refunded fee (VAT-inclusive).', max_digits=10)),
                ('fee_net', models.DecimalField(decimal_places=2, help_text='Refunded fee excluding VAT.', max_digits=10)),
                ('fee_vat', models.DecimalField(decimal_places=2, help_text='Refunded VAT portion.', max_digits=10)),
                ('issued_at', models.DateTimeField(blank=True, help_text='When the credit note was issued.', null=True)),
                ('pdf_file', common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/invoices/credit_notes/')),
                ('payment', models.ForeignKey(blank=True, help_text='The refunded payment that triggered this credit note.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_notes', to='events.payment')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='events.platformfeeinvoice')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='platformfeeinvoice',
            index=models.Index(fields=['organization', 'period_start'], name='idx_invoice_org_period'),
        ),
        migrations.AddIndex(
            model_name='platformfeeinvoice',
            index=models.Index(fields=['status'], name='idx_invoice_status'),
        ),
        migrations.AddConstraint(
            model_name='platformfeeinvoice',
            constraint=models.UniqueConstraint(fields=('organization', 'period_start', 'currency'), name='unique_invoice_per_org_period_currency'),
        ),
    ]
