# Generated by Django 5.2.11 on 2026-03-17 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0055_backpopulate_requires_evaluation_for_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location_maps_url',
            field=models.URLField(blank=True, help_text='Shareable link to Google Maps (e.g., https://goo.gl/maps/...)', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='location_maps_url',
            field=models.URLField(blank=True, help_text='Shareable link to Google Maps (e.g., https://goo.gl/maps/...)', max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='location_maps_url',
            field=models.URLField(blank=True, help_text='Shareable link to Google Maps (e.g., https://goo.gl/maps/...)', max_length=2048, null=True),
        ),
    ]
