# Generated by Django

from django.db import migrations


def create_referral_payout_task(apps, schema_editor):
    """Create periodic task to calculate monthly referral payouts."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Run on the 1st of each month at 06:00 UTC
    monthly_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="6",
        day_of_week="*",
        day_of_month="1",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Calculate monthly referral payouts",
        defaults={
            "task": "events.calculate_referral_payouts",
            "crontab": monthly_schedule,
            "enabled": True,
        },
    )


def delete_referral_payout_task(apps, schema_editor):
    """Remove periodic task for referral payout calculation."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Calculate monthly referral payouts")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0057_organization_billing_name"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_referral_payout_task,
            reverse_code=delete_referral_payout_task,
        ),
    ]
