# Generated by Django 5.2.11 on 2026-03-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0058_add_referral_payout_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='The Stripe Connect Account ID.', max_length=255, null=True, unique=True),
        ),
    ]
