# Generated by Django 5.2.11 on 2026-03-23 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0059_alter_organization_stripe_account_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinvitation',
            name='tier',
        ),
        migrations.RemoveField(
            model_name='eventtoken',
            name='ticket_tier',
        ),
        migrations.RemoveField(
            model_name='pendingeventinvitation',
            name='tier',
        ),
        migrations.AddField(
            model_name='eventinvitation',
            name='tiers',
            field=models.ManyToManyField(blank=True, help_text='Ticket tiers this invitation grants access to (for tier-linked restrictions).', related_name='event_invitations', to='events.tickettier'),
        ),
        migrations.AddField(
            model_name='eventtoken',
            name='ticket_tiers',
            field=models.ManyToManyField(blank=True, help_text='Ticket tiers to assign when users claim this token.', related_name='event_tokens', to='events.tickettier'),
        ),
        migrations.AddField(
            model_name='pendingeventinvitation',
            name='tiers',
            field=models.ManyToManyField(blank=True, help_text='Ticket tiers this invitation grants access to (for tier-linked restrictions).', related_name='pending_event_invitations', to='events.tickettier'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='restrict_purchase_to_linked_invitations',
            field=models.BooleanField(default=False, help_text='When True and purchasable_by includes INVITED, only users whose invitation links to this tier can purchase.'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='restrict_visibility_to_linked_invitations',
            field=models.BooleanField(default=False, help_text='When True and visibility=PRIVATE, only users whose invitation links to this tier can see it.'),
        ),
    ]
