# Generated by Django 5.2.11 on 2026-03-23 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0060_remove_eventinvitation_tier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='public_pronoun_distribution',
            field=models.BooleanField(default=False, help_text='Whether pronoun distribution is visible to non-staff users'),
        ),
    ]
