# Generated by Django 5.2.11 on 2026-03-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0061_event_public_pronoun_distribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalresource',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only'), ('attendees-only', 'Attendees Only')], db_index=True, default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='address_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only'), ('attendees-only', 'Attendees Only')], default='public', help_text='Controls who can see the event address. Uses same rules as resource visibility.', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only')], db_index=True, default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only')], db_index=True, default='private', max_length=20),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only')], db_index=True, default='public', max_length=20),
        ),
    ]
