# Generated by Django 5.2.11 on 2026-03-25 17:22

import common.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0062_alter_additionalresource_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='invoicing_mode',
            field=models.CharField(choices=[('none', 'None'), ('hybrid', 'Hybrid (draft + manual send)'), ('auto', 'Auto (generate + send)')], default='none', help_text='Attendee invoicing mode: none, hybrid (draft + manual send), or auto (generate + send).', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='buyer_billing_snapshot',
            field=models.JSONField(blank=True, default=None, help_text='Buyer billing info snapshot at checkout time for attendee invoice generation.', null=True),
        ),
        migrations.CreateModel(
            name='AttendeeInvoice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('stripe_session_id', models.CharField(db_index=True, max_length=255)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency', models.CharField(max_length=3)),
                ('reverse_charge', models.BooleanField(default=False)),
                ('discount_code_text', models.CharField(blank=True, default='', max_length=64)),
                ('discount_amount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('line_items', models.JSONField(default=list)),
                ('seller_name', models.CharField(max_length=255)),
                ('seller_vat_id', models.CharField(blank=True, default='', max_length=20)),
                ('seller_vat_country', models.CharField(blank=True, default='', max_length=2)),
                ('seller_address', models.TextField(blank=True, default='')),
                ('seller_email', models.EmailField(max_length=254)),
                ('buyer_name', models.CharField(max_length=255)),
                ('buyer_vat_id', models.CharField(blank=True, default='', max_length=20)),
                ('buyer_vat_country', models.CharField(blank=True, default='', max_length=2)),
                ('buyer_address', models.TextField(blank=True, default='')),
                ('buyer_email', models.EmailField(max_length=254)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/invoices/attendee/')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='events.event')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendee_invoices', to='events.organization')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendee_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AttendeeInvoiceCreditNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('credit_note_number', models.CharField(max_length=50, unique=True)),
                ('amount_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_items', models.JSONField(default=list)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('pdf_file', common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/invoices/attendee/credit_notes/')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_notes', to='events.attendeeinvoice')),
                ('payments', models.ManyToManyField(blank=True, related_name='attendee_credit_notes', to='events.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendeeinvoice',
            index=models.Index(fields=['organization', 'created_at'], name='events_atte_organiz_df60cc_idx'),
        ),
        migrations.AddIndex(
            model_name='attendeeinvoice',
            index=models.Index(fields=['user', 'created_at'], name='events_atte_user_id_9ebeff_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendeeinvoice',
            constraint=models.UniqueConstraint(fields=('stripe_session_id',), name='unique_attendee_invoice_per_session'),
        ),
    ]
