# Generated by Django 5.2.11 on 2026-03-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0063_attendee_invoicing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeinvoice',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attendeeinvoicecreditnote',
            name='line_items',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
