# Generated by Django 5.2.11 on 2026-03-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0064_attendee_invoice_line_items_blank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendeeinvoice',
            name='buyer_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='attendeeinvoice',
            name='seller_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
