# Generated by Django 5.2.11 on 2026-04-05 15:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0065_attendee_invoice_email_blank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurrenceRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=10)),
                ('interval', models.PositiveIntegerField(default=1)),
                ('weekdays', models.JSONField(blank=True, default=list)),
                ('monthly_type', models.CharField(blank=True, choices=[('day', 'Day of month'), ('weekday', 'Nth weekday')], max_length=10, null=True)),
                ('day_of_month', models.PositiveIntegerField(blank=True, null=True)),
                ('nth_weekday', models.IntegerField(blank=True, null=True)),
                ('weekday', models.IntegerField(blank=True, null=True)),
                ('dtstart', models.DateTimeField()),
                ('until', models.DateTimeField(blank=True, null=True)),
                ('count', models.PositiveIntegerField(blank=True, null=True)),
                ('rrule_string', models.TextField(blank=True, default='', editable=False)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='is_modified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_template',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='occurrence_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='auto_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='exdates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='generation_window_weeks',
            field=models.PositiveIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='last_generated_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='template_event',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='template_for_series', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventseries',
            name='recurrence_rule',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_series', to='events.recurrencerule'),
        ),
    ]
