# Generated by Django

from django.db import migrations


def create_recurring_events_task(apps, schema_editor):
    """Create periodic task to generate recurring events daily."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Run daily at 4:00 AM UTC
    daily_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="4",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Generate recurring events (rolling window)",
        defaults={
            "task": "events.generate_recurring_events",
            "crontab": daily_schedule,
            "enabled": True,
        },
    )


def delete_recurring_events_task(apps, schema_editor):
    """Remove periodic task for recurring event generation."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Generate recurring events (rolling window)")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0066_recurrencerule_event_is_modified_event_is_template_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_recurring_events_task,
            reverse_code=delete_recurring_events_task,
        ),
    ]
