# Generated by Django 5.2.13 on 2026-04-23 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0067_add_recurring_events_periodic_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="refund_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Actual amount refunded. May be less than amount when a partial refund policy applies.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="payment",
            name="refund_status",
            field=models.CharField(
                blank=True,
                choices=[("pending", "Pending"), ("succeeded", "Succeeded"), ("failed", "Failed")],
                db_index=True,
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="refunded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="stripe_refund_id",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Stripe refund object id. Used to match webhook refund events to this Payment.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cancellation_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cancellation_source",
            field=models.CharField(
                blank=True,
                choices=[
                    ("user", "User self-service"),
                    ("organizer", "Organizer via admin"),
                    ("stripe_dashboard", "Stripe dashboard"),
                ],
                db_index=True,
                default="",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cancelled_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ticket",
            name="refund_policy_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Copy of tier.refund_policy at purchase time. Immutable — drives refund math.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tickettier",
            name="allow_user_cancellation",
            field=models.BooleanField(
                default=False,
                help_text="When True, ticket holders can cancel their own tickets under this tier's refund policy.",
            ),
        ),
        migrations.AddField(
            model_name="tickettier",
            name="cancellation_deadline_hours",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Users can self-cancel up to this many hours before event start. Null = until event start.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tickettier",
            name="refund_policy",
            field=models.JSONField(
                blank=True,
                help_text="Serialized RefundPolicy (tiers + flat fee). Null = allow cancellation with zero refund.",
                null=True,
            ),
        ),
    ]
