# Generated by Django 5.2.13 on 2026-05-08 12:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0068_ticket_cancellation_and_refunds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='contact_method',
            field=models.CharField(choices=[('none', 'None'), ('email', 'Email'), ('form', 'Form')], default='none', help_text='How non-members can reach the organization: NONE hides contact info; EMAIL exposes the verified contact_email; FORM enables the in-platform contact form.', max_length=10),
        ),
        migrations.CreateModel(
            name='OrganizationContactMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('sender_email_snapshot', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_messages', to='events.organization')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', '-created_at'], name='events_orga_organiz_8a3b81_idx')],
            },
        ),
    ]
