# Generated by Django 5.2.14 on 2026-05-11 14:15

import common.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


_EXPIRY_TASK_NAME = "Expire membership subscriptions past grace"


def create_subscription_expiry_task(apps, schema_editor):
    """Register the daily subscription-expiry beat task."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Daily at 04:00 UTC.
    daily_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="4",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name=_EXPIRY_TASK_NAME,
        defaults={
            "task": "events.expire_subscriptions_past_grace",
            "crontab": daily_schedule,
            "enabled": True,
        },
    )


def delete_subscription_expiry_task(apps, schema_editor):
    """Remove the subscription-expiry beat task."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name=_EXPIRY_TASK_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0069_organization_contact_method_and_more'),
        ('django_celery_beat', '0019_alter_periodictasks_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='membership_grace_period_days',
            field=models.PositiveIntegerField(default=7, help_text='Days a PAST_DUE subscription stays valid before expiring.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='membership_refund_policy',
            field=common.fields.MarkdownField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='MembershipSubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(help_text='e.g. "Monthly", "Annual"', max_length=255)),
                ('description', common.fields.MarkdownField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(help_text='ISO 4217 currency code', max_length=3)),
                ('period_unit', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=10)),
                ('period_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscription_plans', to='events.membershiptier')),
            ],
            options={
                'ordering': ['tier__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MembershipSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_subscriptions', to='events.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='events.membershipsubscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='succeeded', max_length=16)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('notes', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_membership_payments', to=settings.AUTH_USER_MODEL)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='events.membershipsubscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subscription', '-created_at'], name='events_memb_subscri_e732d2_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='membershipsubscriptionplan',
            constraint=models.UniqueConstraint(fields=('tier', 'name'), name='unique_plan_name_per_tier'),
        ),
        migrations.AddIndex(
            model_name='membershipsubscription',
            index=models.Index(fields=['organization', 'status'], name='events_memb_organiz_328e24_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipsubscription',
            index=models.Index(fields=['user', 'status'], name='events_memb_user_id_49c809_idx'),
        ),
        migrations.AddConstraint(
            model_name='membershipsubscription',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['cancelled', 'expired']), _negated=True), fields=('user', 'organization'), name='one_active_subscription_per_user_org'),
        ),
        migrations.RunPython(
            create_subscription_expiry_task,
            reverse_code=delete_subscription_expiry_task,
        ),
    ]
