# Generated by Django 5.2.14 on 2026-05-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0070_organization_membership_grace_period_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershippayment',
            name='occurred_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the payment actually changed hands (for backfilled records). Null = use created_at.', null=True),
        ),
    ]
