# Generated by Django 5.2.14 on 2026-05-19 13:10

import uuid

from django.db import migrations, models


SEED_TOKENS = [
    ("demo", "common abuse pattern"),
    ("foo", "common abuse pattern"),
    ("bar", "common abuse pattern"),
    ("baz", "common abuse pattern"),
    ("example", "common abuse pattern"),
    ("sample", "common abuse pattern"),
    ("temp", "common abuse pattern"),
    ("tmp", "common abuse pattern"),
    ("asdf", "common abuse pattern"),
    ("qwerty", "common abuse pattern"),
    ("xxx", "common abuse pattern"),
    ("untitled", "common abuse pattern"),
]


def seed_reserved_slug_tokens(apps, schema_editor) -> None:
    ReservedSlugToken = apps.get_model("events", "ReservedSlugToken")
    ReservedSlugToken.objects.bulk_create(
        [ReservedSlugToken(token=t, reason=r) for t, r in SEED_TOKENS],
        ignore_conflicts=True,
    )


def unseed_reserved_slug_tokens(apps, schema_editor) -> None:
    ReservedSlugToken = apps.get_model("events", "ReservedSlugToken")
    ReservedSlugToken.objects.filter(token__in=[t for t, _ in SEED_TOKENS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0071_membershippayment_occurred_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservedSlugToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('token', models.CharField(max_length=64, unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
            ],
            options={
                'verbose_name': 'Reserved slug token',
                'verbose_name_plural': 'Reserved slug tokens',
                'ordering': ['token'],
            },
        ),
        migrations.RunPython(
            seed_reserved_slug_tokens,
            reverse_code=unseed_reserved_slug_tokens,
        ),
    ]
