# Generated by Django 5.2.14 on 2026-05-20 14:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_reservedslugtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waitlist_batch_size',
            field=models.PositiveIntegerField(default=0, help_text='Number of users to notify per round. 0 = notify all eligible waitlist members simultaneously. Only meaningful when waitlist_time_window is set.'),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_cutoff_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='After this datetime, batching stops. One final all-hands batch fires, then AvailabilityGate behaves normally.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_lottery_mode',
            field=models.BooleanField(default=False, help_text='If True, randomly sample batch members instead of FIFO.'),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_time_window',
            field=models.DurationField(blank=True, help_text='Time window for a batch to claim spots. NULL = legacy passive waitlist (no offers, no batching, current default behavior).', null=True),
        ),
        migrations.CreateModel(
            name='WaitlistOffer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('claimed', 'Claimed'), ('expired', 'Expired'), ('revoked', 'Revoked')], db_index=True, default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('batch_id', models.UUIDField(db_index=True)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('is_cutoff_batch', models.BooleanField(default=False)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offers', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_offers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event', 'status', 'expires_at'], name='events_wait_event_i_cdc5d6_idx'), models.Index(fields=['batch_id'], name='events_wait_batch_i_ec4840_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('event', 'user'), name='unique_pending_waitlist_offer')],
            },
        ),
    ]
