# Generated by Django 5.2.14 on 2026-05-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0072_reservedslugtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='waitlist_batch_size',
            field=models.PositiveIntegerField(default=0, help_text='Number of users to notify per round. 0 = notify all eligible waitlist members simultaneously. Only meaningful when waitlist_time_window is set.'),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_cutoff_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='After this datetime, batching stops. One final all-hands batch fires, then AvailabilityGate behaves normally.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_cutoff_window',
            field=models.DurationField(blank=True, help_text='Time window for the cutoff all-hands batch. Falls back to waitlist_time_window when null.', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_lottery_mode',
            field=models.BooleanField(default=False, help_text='If True, randomly sample batch members instead of FIFO.'),
        ),
        migrations.AddField(
            model_name='event',
            name='waitlist_time_window',
            field=models.DurationField(blank=True, help_text='Time window for a batch to claim spots. NULL = legacy passive waitlist (no offers, no batching, current default behavior).', null=True),
        ),
    ]
