# Generated by Django 5.2.14 on 2026-06-01 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0076_eventbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
