# Generated by Django 5.2.15 on 2026-06-11 08:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0077_event_cancellation_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=100)),
                ('account', models.CharField(blank=True, db_index=True, default='', help_text='Stripe Connect account id (event.account); empty for platform-endpoint events.', max_length=255)),
                ('livemode', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('outcome', models.CharField(choices=[('processing', 'Processing'), ('handled', 'Handled'), ('unhandled', 'Unhandled')], db_index=True, default='processing', max_length=16)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
