# Generated by Django 5.2.14 on 2026-05-28 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_stripe_webhook_event_prune_periodic_task'),
        ('questionnaires', '0012_alter_questionnaire_llm_backend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='organizationmembershiprequest',
            name='unique_organization_user_membership_request',
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='membership_questionnaire',
            field=models.ForeignKey(blank=True, help_text='Tier-specific membership questionnaire. NULL = inherit org default.', limit_choices_to={'questionnaire_type': 'membership'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.organizationquestionnaire'),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='requires_membership_approval',
            field=models.BooleanField(blank=True, default=None, help_text='Tier-specific manual-approval override. NULL = inherit org.default_requires_membership_approval.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_membership_questionnaire',
            field=models.ForeignKey(blank=True, help_text='Default membership questionnaire applied to all tiers (overridable per tier).', limit_choices_to={'questionnaire_type': 'membership'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.organizationquestionnaire'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_requires_membership_approval',
            field=models.BooleanField(default=False, help_text='When True, every membership application requires manual staff approval.'),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Target plan for paid path. NULL = free join. Phase 1 rejects non-null at /apply.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_applications', to='events.membershipsubscriptionplan'),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='questionnaire_submission',
            field=models.ForeignKey(blank=True, help_text='Submission that satisfied the questionnaire gate, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questionnaires.questionnairesubmission'),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_application', to='events.membershipsubscription'),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Target tier. NULL = tier-less legacy application; staff picks at approval.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_applications', to='events.membershiptier'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='organizationmembershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'user', 'tier'), name='unique_pending_application_per_user_org_tier', nulls_distinct=False),
        ),
    ]
