# Generated by Django 5.2.15 on 2026-06-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0079_stripe_webhook_event_prune_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='offline_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Amount refunded for a manually-collected offline/at-the-door ticket. Null means the ticket was never refunded (a plain cancellation). Online (Stripe) refunds are tracked on Payment.refund_amount instead.', max_digits=10, null=True),
        ),
    ]
