# Generated by Django 5.2.15 on 2026-06-16 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0080_ticket_offline_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='resend_to_new_signups',
            field=models.BooleanField(default=False, help_text='Re-deliver to attendees who join after this announcement was first sent (event announcements only).'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='schedule_anchor',
            field=models.CharField(blank=True, choices=[('event_start', 'Event start'), ('event_end', 'Event end')], help_text='Anchor a relative schedule to the event start or end.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='schedule_offset_minutes',
            field=models.IntegerField(blank=True, help_text='Signed minutes from the anchor (-1440 = 24h before, +1440 = 24h after).', null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Absolute time to send a scheduled announcement (mutually exclusive with relative scheduling).', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sent', 'Sent')], db_index=True, default='draft', max_length=20),
        ),
    ]
