# Generated by Django 5.2.15 on 2026-06-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0082_announcement_periodic_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='schedule',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of timeline sessions (relative offsets from event start). Display-only.'),
        ),
    ]
