# Generated by Django 5.2.15 on 2026-06-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0083_event_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='last_revenue_report_sent_period',
            field=models.CharField(blank=True, default='', help_text="Last period for which a revenue report was sent (e.g. '2024-Q1' or '2024-03').", max_length=16),
        ),
        migrations.AddField(
            model_name='organization',
            name='revenue_report_cadence',
            field=models.CharField(choices=[('none', 'None'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly')], default='none', help_text="Cadence for emailed revenue & VAT reports. Requires billing_email when not 'none'.", max_length=10),
        ),
    ]
