# Generated by Django 5.2.15 on 2026-06-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0085_revenue_report_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_open_ended',
            field=models.BooleanField(default=False, help_text='If True, the event has no fixed end shown to attendees. `end` is still set (defaulting to start + 24h) and used internally as an operational horizon.'),
        ),
    ]
