# Generated by Django 5.2.15 on 2026-06-24 11:03

import typing as t

from django.db import migrations, models
from django.db.models import F
from django.db.models.functions import Coalesce


def backfill_email_sent_at(apps: t.Any, schema_editor: t.Any) -> None:
    """Mark pre-existing issued documents as already delivered (issue #616).

    Without this, every invoice/credit note/platform-fee invoice created before
    the field existed has ``email_sent_at`` null, so the new 15-minute recovery
    sweep would treat every already-emailed document as undelivered and re-send
    it. Backfill ``issued_at`` (falling back to ``created_at``) for the rows the
    sweep selects so it only targets genuinely undelivered records going forward.
    """
    AttendeeInvoice = apps.get_model("events", "AttendeeInvoice")
    AttendeeInvoiceCreditNote = apps.get_model("events", "AttendeeInvoiceCreditNote")
    PlatformFeeInvoice = apps.get_model("events", "PlatformFeeInvoice")

    # Attendee invoices: the sweep only re-dispatches ISSUED rows.
    AttendeeInvoice.objects.filter(status="issued", email_sent_at__isnull=True).update(
        email_sent_at=Coalesce(F("issued_at"), F("created_at"))
    )
    # Credit notes have no status — the sweep selects them all.
    AttendeeInvoiceCreditNote.objects.filter(email_sent_at__isnull=True).update(
        email_sent_at=Coalesce(F("issued_at"), F("created_at"))
    )
    # Platform-fee invoices: the sweep only re-dispatches ISSUED rows.
    PlatformFeeInvoice.objects.filter(status="issued", email_sent_at__isnull=True).update(
        email_sent_at=Coalesce(F("issued_at"), F("created_at"))
    )


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0087_reanchor_non_utc_series_occurrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeinvoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the document was successfully emailed to its recipient.', null=True),
        ),
        migrations.AddField(
            model_name='attendeeinvoicecreditnote',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the document was successfully emailed to its recipient.', null=True),
        ),
        migrations.AddField(
            model_name='platformfeeinvoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='When the document was successfully emailed to its recipient.', null=True),
        ),
        migrations.RunPython(backfill_email_sent_at, migrations.RunPython.noop),
    ]
