# Generated by Django 5.2.15 on 2026-06-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0087_reanchor_non_utc_series_occurrences'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendeeinvoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the document was successfully emailed to its recipient.', null=True),
        ),
        migrations.AddField(
            model_name='attendeeinvoicecreditnote',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the document was successfully emailed to its recipient.', null=True),
        ),
        migrations.AddField(
            model_name='platformfeeinvoice',
            name='email_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the document was successfully emailed to its recipient.', null=True),
        ),
    ]
