# Generated by Django

from django.db import migrations

TASK_NAME = "Re-dispatch undelivered invoices (delivery backstop)"


def create_redispatch_task(apps, schema_editor):
    """Create the periodic task that re-dispatches undelivered invoices."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="*/15",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name=TASK_NAME,
        defaults={
            "task": "events.redispatch_undelivered_invoices",
            "crontab": schedule,
            "enabled": True,
        },
    )


def delete_redispatch_task(apps, schema_editor):
    """Remove the periodic task."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")
    PeriodicTask.objects.filter(name=TASK_NAME).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0088_attendeeinvoice_email_sent_at_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_redispatch_task,
            reverse_code=delete_redispatch_task,
        ),
    ]
