# Generated by Django 5.2.15 on 2026-07-08 07:55

import common.fields
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0090_attendeeinvoice_email_delivery_error_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeriesPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only')], db_index=True, default='public', max_length=20)),
                ('description', common.fields.MarkdownField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('pro_rata_discount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('payment_method', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('at_the_door', 'At The Door'), ('free', 'Free')], db_index=True, default='online', max_length=20)),
                ('purchasable_by', models.CharField(choices=[('public', 'General public'), ('members', 'Members only'), ('invited', 'Invitees only'), ('invited_and_members', 'Invited and Members only')], db_index=True, default='public', max_length=20)),
                ('sales_start_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('sales_end_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('total_quantity', models.PositiveIntegerField(blank=True, default=None, null=True)),
                ('quantity_sold', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['event_series', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeriesPassTierLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeldSeriesPass',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('price_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stripe_session_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('pdf_file', common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/series_passes/pdf/')),
                ('pkpass_file', common.fields.ProtectedFileField(blank=True, null=True, upload_to='protected/series_passes/pkpass/')),
                ('file_content_hash', models.CharField(blank=True, max_length=64, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='held_series_passes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='held_pass',
            field=models.ForeignKey(blank=True, help_text='Set when this ticket was materialized from a series pass purchase.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='events.heldseriespass'),
        ),
        migrations.AddConstraint(
            model_name='ticket',
            constraint=models.UniqueConstraint(condition=models.Q(('held_pass__isnull', False), models.Q(('status', 'cancelled'), _negated=True)), fields=('held_pass', 'event'), name='unique_held_pass_ticket_per_event'),
        ),
        migrations.AddField(
            model_name='seriespass',
            name='event_series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_passes', to='events.eventseries'),
        ),
        migrations.AddField(
            model_name='heldseriespass',
            name='series_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='held_passes', to='events.seriespass'),
        ),
        migrations.AddField(
            model_name='seriespasstierlink',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_pass_links', to='events.event'),
        ),
        migrations.AddField(
            model_name='seriespasstierlink',
            name='series_pass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tier_links', to='events.seriespass'),
        ),
        migrations.AddField(
            model_name='seriespasstierlink',
            name='tier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_pass_links', to='events.tickettier'),
        ),
        migrations.AddConstraint(
            model_name='seriespass',
            constraint=models.UniqueConstraint(fields=('event_series', 'name'), name='unique_series_pass_name'),
        ),
        migrations.AddConstraint(
            model_name='heldseriespass',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('series_pass', 'user'), name='unique_active_held_pass_per_user'),
        ),
        migrations.AddConstraint(
            model_name='seriespasstierlink',
            constraint=models.UniqueConstraint(fields=('series_pass', 'event'), name='unique_series_pass_event'),
        ),
    ]
