# Generated by Django 5.2.15 on 2026-07-07 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_seriespass_seriespasstierlink_heldseriespass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seriespass',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('unlisted', 'Unlisted'), ('private', 'Private'), ('members-only', 'Members Only'), ('staff-only', 'Staff Only')], db_index=True, default='public', max_length=20),
        ),
    ]
