# Generated by Django 5.2.16 on 2026-07-12 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0091_seriespass_seriespasstierlink_heldseriespass_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membershiptier',
            options={'ordering': ['organization', 'display_order', 'name']},
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='display_order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='membershiptier',
            index=models.Index(fields=['organization', 'display_order'], name='events_memb_organiz_e5b71e_idx'),
        ),
    ]
