# Generated by Django 5.2.15 on 2026-07-07 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0092_alter_seriespass_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='held_pass',
            field=models.ForeignKey(blank=True, help_text='Set when this ticket was materialized from a series pass purchase.', null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='tickets', to='events.heldseriespass'),
        ),
    ]
