# Generated by Django 5.2.16 on 2026-07-13 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0093_backfill_membership_tier_display_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='reservation_id',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
