# Generated by Django 5.2.16 on 2026-07-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0095_backfill_payment_reservation_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='accept_rsvp_notes',
            field=models.BooleanField(default=False, help_text='Allow attendees to attach a short plain-text note to their RSVP.'),
        ),
        migrations.AddField(
            model_name='eventrsvp',
            name='note',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
