# Generated by Django 5.2.16 on 2026-07-18 12:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_rsvp_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeatOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('held', 'Held (house/tech/promoter)'), ('killed', 'Killed (not sellable this event)')], db_index=True, max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Hex color for map rendering, e.g. #aa0000.', max_length=7)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['venue', 'display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('guest_session', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('acquired_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='venueseat',
            options={'ordering': ['sector', 'row_order', 'adjacency_index', 'label']},
        ),
        migrations.RemoveIndex(
            model_name='venueseat',
            name='events_venu_sector__33fcd5_idx',
        ),
        migrations.RenameField(
            model_name='venueseat',
            old_name='row',
            new_name='row_label',
        ),
        migrations.AddField(
            model_name='venueseat',
            name='adjacency_index',
            field=models.PositiveIntegerField(default=0, help_text='Physical left-to-right position in the row. Never derived from printed number.'),
        ),
        migrations.AddField(
            model_name='venueseat',
            name='row_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Deterministic front-to-back row rank within the sector.'),
        ),
        migrations.AddField(
            model_name='venuesector',
            name='kind',
            field=models.CharField(choices=[('seated', 'Seated'), ('standing', 'Standing')], db_index=True, default='seated', max_length=10),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='seat_assignment_mode',
            field=models.CharField(choices=[('none', 'No seat assignment (GA/standing)'), ('best_available', 'Best available (adjacency-aware)'), ('user_choice', 'User chooses seat')], db_index=True, default='none', help_text='How seats are assigned for tickets in this tier.', max_length=20),
        ),
        migrations.AddField(
            model_name='eventseatoverride',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_overrides', to='events.event'),
        ),
        migrations.AddField(
            model_name='eventseatoverride',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_overrides', to='events.venueseat'),
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_categories', to='events.venue'),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='price_category',
            field=models.ForeignKey(blank=True, help_text='Seated tiers draw seats from this category. Multiple tiers may share one category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_tiers', to='events.pricecategory'),
        ),
        migrations.AddField(
            model_name='venueseat',
            name='default_price_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='events.pricecategory'),
        ),
        migrations.AddIndex(
            model_name='venueseat',
            index=models.Index(fields=['sector', 'row_label', 'number'], name='events_venu_sector__7b5948_idx'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='events.event'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='seat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='events.venueseat'),
        ),
        migrations.AddField(
            model_name='seathold',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='eventseatoverride',
            index=models.Index(fields=['event', 'status'], name='events_even_event_i_346bec_idx'),
        ),
        migrations.AddConstraint(
            model_name='eventseatoverride',
            constraint=models.UniqueConstraint(fields=('event', 'seat'), name='unique_event_seat_override'),
        ),
        migrations.AddConstraint(
            model_name='pricecategory',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_venue_price_category_name'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['event', 'user'], name='events_seat_event_i_7c3228_idx'),
        ),
        migrations.AddIndex(
            model_name='seathold',
            index=models.Index(fields=['event', 'guest_session'], name='events_seat_event_i_702f4a_idx'),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.UniqueConstraint(fields=('event', 'seat'), name='unique_seathold_event_seat'),
        ),
        migrations.AlterField(
            model_name='venuesector',
            name='shape',
            field=models.JSONField(blank=True, help_text='Arbitrary polygon for FE rendering. Canonical format: [{"x": .., "y": ..}, ...]. Legacy [x, y] pairs are coerced on read.', null=True),
        ),
        migrations.AddConstraint(
            model_name='seathold',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('guest_session', '')), models.Q(('user__isnull', True), models.Q(('guest_session', ''), _negated=True)), _connector='OR'), name='seathold_exactly_one_owner'),
        ),
    ]
