# Generated by Django 5.2.16 on 2026-07-17 17:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0096_rsvp_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(help_text='Hex color for map rendering, e.g. #aa0000.', max_length=7)),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['venue', 'display_order', 'name'],
            },
        ),
        migrations.AlterModelOptions(
            name='venueseat',
            options={'ordering': ['sector', 'row_order', 'adjacency_index', 'label']},
        ),
        migrations.RemoveIndex(
            model_name='venueseat',
            name='events_venu_sector__33fcd5_idx',
        ),
        migrations.RenameField(
            model_name='venueseat',
            old_name='row',
            new_name='row_label',
        ),
        migrations.AddField(
            model_name='venueseat',
            name='adjacency_index',
            field=models.PositiveIntegerField(default=0, help_text='Physical left-to-right position in the row. Never derived from printed number.'),
        ),
        migrations.AddField(
            model_name='venueseat',
            name='row_order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Deterministic front-to-back row rank within the sector.'),
        ),
        migrations.AddField(
            model_name='venuesector',
            name='kind',
            field=models.CharField(choices=[('seated', 'Seated'), ('standing', 'Standing')], db_index=True, default='seated', max_length=10),
        ),
        migrations.AddField(
            model_name='pricecategory',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_categories', to='events.venue'),
        ),
        migrations.AddField(
            model_name='venueseat',
            name='default_price_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seats', to='events.pricecategory'),
        ),
        migrations.AddIndex(
            model_name='venueseat',
            index=models.Index(fields=['sector', 'row_label', 'number'], name='events_venu_sector__7b5948_idx'),
        ),
        migrations.AddConstraint(
            model_name='pricecategory',
            constraint=models.UniqueConstraint(fields=('venue', 'name'), name='unique_venue_price_category_name'),
        ),
    ]
