# Generated by Django 5.2.16 on 2026-07-17 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0098_seat_row_adjacency_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='price_category',
            field=models.ForeignKey(blank=True, help_text='Seated tiers draw seats from this category. Multiple tiers may share one category.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_tiers', to='events.pricecategory'),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='seat_assignment_mode',
            field=models.CharField(choices=[('none', 'No seat assignment (GA/standing)'), ('random', 'Random assignment at purchase'), ('best_available', 'Best available (adjacency-aware)'), ('user_choice', 'User chooses seat')], db_index=True, default='none', help_text='How seats are assigned for tickets in this tier.', max_length=20),
        ),
    ]
