# Generated by Django 5.2.16 on 2026-07-17 17:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0099_tickettier_price_category_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSeatOverride',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('held', 'Held (house/tech/promoter)'), ('killed', 'Killed (not sellable this event)')], db_index=True, max_length=10)),
                ('reason', models.CharField(blank=True, default='', max_length=255)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_overrides', to='events.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_overrides', to='events.venueseat')),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'status'], name='events_even_event_i_346bec_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'seat'), name='unique_event_seat_override')],
            },
        ),
        migrations.CreateModel(
            name='SeatHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('guest_session', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('acquired_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to='events.event')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='events.venueseat')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='seat_holds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['event', 'user'], name='events_seat_event_i_7c3228_idx'), models.Index(fields=['event', 'guest_session'], name='events_seat_event_i_702f4a_idx')],
                'constraints': [models.UniqueConstraint(fields=('event', 'seat'), name='unique_seathold_event_seat'), models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('guest_session', '')), models.Q(('user__isnull', True), models.Q(('guest_session', ''), _negated=True)), _connector='OR'), name='seathold_exactly_one_owner')],
            },
        ),
    ]
