# Generated by Django 5.2.16 on 2026-07-21 13:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0100_add_cleanup_expired_seat_holds_periodic_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='incident_hold_at',
            field=models.DateTimeField(blank=True, help_text='Evidence hold for a recorded money-correctness incident. While set, the payment expiry sweep retains this row; clear it once the incident is resolved to release the row back to the normal cleanup schedule.', null=True),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('incident_hold_at__isnull', False)), fields=['incident_hold_at'], name='payment_incident_hold_idx'),
        ),
    ]
