# Generated by Django 5.2.16 on 2026-07-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0100_add_cleanup_expired_seat_holds_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='metadata',
            field=models.JSONField(blank=True, default=None, help_text='Arbitrary JSON for venue-level layout config (e.g. stage position/shape) written by the frontend designer.', null=True),
        ),
    ]
