# Generated by Django 5.2.16 on 2026-07-24 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0100_subscription_reconcile_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembershipsubscriptionplan',
            name='max_subscriptions',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Cap on concurrent non-terminal subscriptions (the venue's card stock). Cancelled/expired subscriptions free their slot automatically. NULL = unlimited.", null=True),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscriptionplan',
            name='sales_status',
            field=models.CharField(choices=[('open', 'Open'), ('paused', 'Paused')], default='open', help_text='PAUSED stops member self-service sales (subscribe, revive, plan switches into this plan) while leaving existing subscribers untouched. Orthogonal to archiving: an archived plan is retired, a paused one is temporarily closed.', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipsubscriptionplan',
            name='max_subscriptions',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Cap on concurrent non-terminal subscriptions (the venue's card stock). Cancelled/expired subscriptions free their slot automatically. NULL = unlimited.", null=True),
        ),
        migrations.AddField(
            model_name='membershipsubscriptionplan',
            name='sales_status',
            field=models.CharField(choices=[('open', 'Open'), ('paused', 'Paused')], default='open', help_text='PAUSED stops member self-service sales (subscribe, revive, plan switches into this plan) while leaving existing subscribers untouched. Orthogonal to archiving: an archived plan is retired, a paused one is temporarily closed.', max_length=10),
        ),
    ]
