# Generated by Django 5.2.16 on 2026-07-24 21:29

import common.fields
import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0100_add_cleanup_expired_seat_holds_periodic_task'),
        ('questionnaires', '0012_alter_questionnaire_llm_backend'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalCustomerProfile',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('stripe_customer_id', models.CharField(db_index=True, max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical customer profile',
                'verbose_name_plural': 'historical customer profiles',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembershipPayment',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='succeeded', max_length=16)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('occurred_at', models.DateTimeField(blank=True, db_index=True, help_text='When the payment actually changed hands (for backfilled records). Null = use created_at.', null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('raw_response', models.JSONField(blank=True, default=dict)),
                ('stripe_invoice_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical membership payment',
                'verbose_name_plural': 'historical membership payments',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembershipSubscription',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('stripe_schedule_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('expired_at', models.DateTimeField(blank=True, help_text='Set when status transitions to EXPIRED. Used for the revival window check.', null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical membership subscription',
                'verbose_name_plural': 'historical membership subscriptions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMembershipSubscriptionPlan',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, editable=False)),
                ('name', models.CharField(help_text='e.g. "Monthly", "Annual"', max_length=255)),
                ('description', common.fields.MarkdownField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(help_text='ISO 4217 currency code', max_length=3)),
                ('period_unit', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=10)),
                ('period_count', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sales_status', models.CharField(choices=[('open', 'Open'), ('paused', 'Paused')], default='open', help_text='PAUSED stops member self-service sales (subscribe, revive, plan switches into this plan) while leaving existing subscribers untouched. Orthogonal to archiving: an archived plan is retired, a paused one is temporarily closed.', max_length=10)),
                ('max_subscriptions', models.PositiveIntegerField(blank=True, default=None, help_text="Cap on concurrent non-terminal subscriptions (the venue's card stock). Cancelled/expired subscriptions free their slot automatically. NULL = unlimited.", null=True)),
                ('payment_method', models.CharField(choices=[('online', 'Online (Stripe)'), ('offline', 'Offline (staff-managed)')], default='offline', help_text='ONLINE plans are billed via Stripe; OFFLINE plans are tracked manually by staff.', max_length=10)),
                ('stripe_product_id', models.CharField(blank=True, default='', max_length=255)),
                ('stripe_price_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical membership subscription plan',
                'verbose_name_plural': 'historical membership subscription plans',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveConstraint(
            model_name='organizationmembershiprequest',
            name='unique_organization_user_membership_request',
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='stripe_invoice_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='stripe_payment_intent_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='membershipsubscription',
            name='expired_at',
            field=models.DateTimeField(blank=True, help_text='Set when status transitions to EXPIRED. Used for the revival window check.', null=True),
        ),
        migrations.AddField(
            model_name='membershipsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, help_text='Plan that will replace ``plan`` at the next renewal (downgrade flow).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pending_subscriptions', to='events.membershipsubscriptionplan'),
        ),
        migrations.AddField(
            model_name='membershipsubscription',
            name='stripe_schedule_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='membershipsubscription',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='membershipsubscriptionplan',
            name='max_subscriptions',
            field=models.PositiveIntegerField(blank=True, default=None, help_text="Cap on concurrent non-terminal subscriptions (the venue's card stock). Cancelled/expired subscriptions free their slot automatically. NULL = unlimited.", null=True),
        ),
        migrations.AddField(
            model_name='membershipsubscriptionplan',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (Stripe)'), ('offline', 'Offline (staff-managed)')], default='offline', help_text='ONLINE plans are billed via Stripe; OFFLINE plans are tracked manually by staff.', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipsubscriptionplan',
            name='sales_status',
            field=models.CharField(choices=[('open', 'Open'), ('paused', 'Paused')], default='open', help_text='PAUSED stops member self-service sales (subscribe, revive, plan switches into this plan) while leaving existing subscribers untouched. Orthogonal to archiving: an archived plan is retired, a paused one is temporarily closed.', max_length=10),
        ),
        migrations.AddField(
            model_name='membershipsubscriptionplan',
            name='stripe_price_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='membershipsubscriptionplan',
            name='stripe_product_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='membership_questionnaire',
            field=models.ForeignKey(blank=True, help_text='Tier-specific membership questionnaire. NULL = inherit org default.', limit_choices_to={'questionnaire_type': 'membership'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.organizationquestionnaire'),
        ),
        migrations.AddField(
            model_name='membershiptier',
            name='requires_membership_approval',
            field=models.BooleanField(blank=True, default=None, help_text='Tier-specific manual-approval override. NULL = inherit org.default_requires_membership_approval.', null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_membership_questionnaire',
            field=models.ForeignKey(blank=True, help_text='Default membership questionnaire applied to all tiers (overridable per tier).', limit_choices_to={'questionnaire_type': 'membership'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.organizationquestionnaire'),
        ),
        migrations.AddField(
            model_name='organization',
            name='default_requires_membership_approval',
            field=models.BooleanField(default=False, help_text='When True, every membership application requires manual staff approval.'),
        ),
        migrations.AddField(
            model_name='organization',
            name='membership_subscription_revival_window_days',
            field=models.PositiveIntegerField(default=30, help_text='Days after subscription expiry during which a member can revive in place. Set to 0 to disable revival entirely.'),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Target plan for paid path. NULL = free join. Phase 1 rejects non-null at /apply.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_applications', to='events.membershipsubscriptionplan'),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='questionnaire_submission',
            field=models.ForeignKey(blank=True, help_text='Submission that satisfied the questionnaire gate, if applicable.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='questionnaires.questionnairesubmission'),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_application', to='events.membershipsubscription'),
        ),
        migrations.AddField(
            model_name='organizationmembershiprequest',
            name='tier',
            field=models.ForeignKey(blank=True, help_text='Target tier. NULL = tier-less legacy application; staff picks at approval.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_applications', to='events.membershiptier'),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='organizationmembershiprequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('organization', 'user', 'tier'), name='unique_pending_application_per_user_org_tier', nulls_distinct=False),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to='events.organization'),
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomerprofile',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalcustomerprofile',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.organization'),
        ),
        migrations.AddField(
            model_name='historicalcustomerprofile',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershippayment',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershippayment',
            name='recorded_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershippayment',
            name='subscription',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.membershipsubscription'),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscription',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscription',
            name='organization',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.organization'),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscription',
            name='pending_plan',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Plan that will replace ``plan`` at the next renewal (downgrade flow).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.membershipsubscriptionplan'),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscription',
            name='plan',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.membershipsubscriptionplan'),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscription',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscriptionplan',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscriptionplan',
            name='tier',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.membershiptier'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(fields=('user', 'organization'), name='unique_customer_per_user_org'),
        ),
        migrations.AddConstraint(
            model_name='customerprofile',
            constraint=models.UniqueConstraint(fields=('organization', 'stripe_customer_id'), name='unique_stripe_customer_per_org'),
        ),
        migrations.AddField(
            model_name='historicalmembershipsubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hosted Checkout Session that will (or did) create the Stripe Subscription.', max_length=255),
        ),
        migrations.AddField(
            model_name='membershipsubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hosted Checkout Session that will (or did) create the Stripe Subscription.', max_length=255),
        ),
    ]
