# Generated by Django 5.2.16 on 2026-07-18 12:10

import typing as t

from django.db import migrations, models

if t.TYPE_CHECKING:
    from django.apps.registry import Apps
    from django.db.backends.base.schema import BaseDatabaseSchemaEditor


def convert_random_tiers(apps: "Apps", schema_editor: "BaseDatabaseSchemaEditor") -> None:
    """Map removed RANDOM mode: BEST_AVAILABLE when a price category exists, else USER_CHOICE.

    A BEST_AVAILABLE tier without a price category would be unsellable
    (load_candidates draws from the category's seat pool), so category-less
    RANDOM tiers keep their sector semantics as USER_CHOICE.
    """
    TicketTier = apps.get_model("events", "TicketTier")
    TicketTier.objects.filter(seat_assignment_mode="random", price_category__isnull=False).update(
        seat_assignment_mode="best_available"
    )
    TicketTier.objects.filter(seat_assignment_mode="random").update(seat_assignment_mode="user_choice")


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0101_add_cleanup_expired_seat_holds_periodic_task"),
    ]

    operations = [
        migrations.RunPython(convert_random_tiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="tickettier",
            name="seat_assignment_mode",
            field=models.CharField(
                choices=[
                    ("none", "No seat assignment (GA/standing)"),
                    ("best_available", "Best available (adjacency-aware)"),
                    ("user_choice", "User chooses seat"),
                ],
                db_index=True,
                default="none",
                help_text="How seats are assigned for tickets in this tier.",
                max_length=20,
            ),
        ),
    ]
