# Generated by Django 5.2.16 on 2026-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_venue_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='category_prices',
            field=models.JSONField(blank=True, default=dict, help_text='{price_category_id: price} for user-choice tiers. Empty = flat pricing.'),
        ),
    ]
