# Generated by Django 5.2.16 on 2026-07-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0101_venue_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='category_prices',
            field=models.JSONField(blank=True, default=dict, help_text='{price_category_id: price} for user-choice tiers. Empty = flat pricing.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Amount paid for THIS ticket, when tier.price alone cannot reconstruct it: PWYC, a discount code, or a tier that prices seats per category. Null for online payments (Payment.amount is authoritative there — it is net for a reverse-charge buyer, so stamping it here would put two different 'price paid' numbers on one row) and null for a plain purchase on a flat tier (use tier.price).", max_digits=10, null=True),
        ),
    ]
