# Generated by Django 5.2.16 on 2026-07-20 22:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0102_tickettier_category_prices'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='chart_version',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Version stamp of the seating chart; bumped by every chart-visible venue write.'),
        ),
    ]
