# Generated by Django 5.2.16 on 2026-07-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_subscription_reconcile_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembershipsubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hosted Checkout Session that will (or did) create the Stripe Subscription.', max_length=255),
        ),
        migrations.AddField(
            model_name='membershipsubscription',
            name='stripe_checkout_session_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Hosted Checkout Session that will (or did) create the Stripe Subscription.', max_length=255),
        ),
    ]
