# Generated by Django 5.2.16 on 2026-07-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_subscription_reconcile_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='visibility_settings',
            field=models.JSONField(blank=True, default=dict, help_text="Granular switches for organizational information (attendee count, capacity, guest list). An empty object means every toggle keeps its default of 'visible'."),
        ),
    ]
