# Generated by Django 5.2.16 on 2026-07-25 23:46

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_subscription_reconcile_beat'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmembershippayment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross platform fee taken on this payment (0 for offline/failed payments).', max_digits=10),
        ),
        migrations.AddField(
            model_name='historicalmembershippayment',
            name='platform_fee_net',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee excluding VAT.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalmembershippayment',
            name='platform_fee_reverse_charge',
            field=models.BooleanField(default=False, help_text='Whether reverse charge applies to the platform fee (EU B2B cross-border).'),
        ),
        migrations.AddField(
            model_name='historicalmembershippayment',
            name='platform_fee_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT portion of the platform fee.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='historicalmembershippayment',
            name='platform_fee_vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee VAT rate snapshot.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Gross platform fee taken on this payment (0 for offline/failed payments).', max_digits=10),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='platform_fee_net',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee excluding VAT.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='platform_fee_reverse_charge',
            field=models.BooleanField(default=False, help_text='Whether reverse charge applies to the platform fee (EU B2B cross-border).'),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='platform_fee_vat',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='VAT portion of the platform fee.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='membershippayment',
            name='platform_fee_vat_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Platform fee VAT rate snapshot.', max_digits=5, null=True),
        ),
    ]
