# Generated by Django 5.2.16 on 2026-07-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0103_venue_chart_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickettier',
            name='price_category',
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='category_prices',
            field=models.JSONField(blank=True, default=dict, help_text='{price_category_id: price}. Empty = flat pricing.'),
        ),
    ]
