# Generated by Django 5.2.16 on 2026-07-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0104_historicalmembershippayment_platform_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformfeeinvoice',
            name='total_subscription_payments',
            field=models.PositiveIntegerField(default=0, help_text='Number of membership subscription payments in this period.'),
        ),
        migrations.AddField(
            model_name='platformfeeinvoice',
            name='total_subscription_revenue',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total membership subscription revenue in this period.', max_digits=12),
        ),
    ]
