# Generated by Django 5.2.16 on 2026-07-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0105_backfill_visibility_settings_from_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='visibility_settings',
            field=models.JSONField(blank=True, default=dict, help_text='Granular disclosure settings: boolean toggles for attendee count, capacity, guest list, and pronoun distribution, plus an address_visibility level (public/private/members-only/staff-only/attendees-only). An empty object means every toggle keeps its own default — visible for all of them except pronoun distribution, which defaults to hidden; address_visibility defaults to public.'),
        ),
    ]
