# Generated by Django 5.2.16 on 2026-07-29 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0105_backfill_visibility_settings_from_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address_visibility',
        ),
        migrations.RemoveField(
            model_name='event',
            name='public_pronoun_distribution',
        ),
    ]
