# Generated by Django 5.2.16 on 2026-07-30 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0106_remove_event_address_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptier',
            name='membership_questionnaire',
            field=models.ForeignKey(blank=True, help_text='Tier-specific membership questionnaire. NULL = inherit org default.', limit_choices_to={'questionnaire_type': 'membership'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tiers', to='events.organizationquestionnaire'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='default_membership_questionnaire',
            field=models.ForeignKey(blank=True, help_text='Default membership questionnaire applied to all tiers (overridable per tier).', limit_choices_to={'questionnaire_type': 'membership'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_organizations', to='events.organizationquestionnaire'),
        ),
    ]
