# Generated by Django 5.2.16 on 2026-07-30 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0108_stale_approved_application_beat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='plan',
            field=models.ForeignKey(blank=True, help_text='Target plan for the paid path. NULL = free join.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='membership_applications', to='events.membershipsubscriptionplan'),
        ),
    ]
