# Generated by Django 5.2.16 on 2026-07-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0109_alter_organizationmembershiprequest_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmembershipsubscriptionplan',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (Stripe)'), ('offline', 'Offline (staff-managed)'), ('free', 'Free (member self-serve)')], default='offline', help_text='ONLINE plans are billed via Stripe; OFFLINE plans are tracked manually by staff; FREE plans cost nothing, are self-serve, and never renew (price 0 + LIFETIME period).', max_length=10),
        ),
        migrations.AlterField(
            model_name='historicalmembershipsubscriptionplan',
            name='period_unit',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year'), ('lifetime', 'Lifetime')], default='month', max_length=10),
        ),
        migrations.AlterField(
            model_name='membershipsubscriptionplan',
            name='payment_method',
            field=models.CharField(choices=[('online', 'Online (Stripe)'), ('offline', 'Offline (staff-managed)'), ('free', 'Free (member self-serve)')], default='offline', help_text='ONLINE plans are billed via Stripe; OFFLINE plans are tracked manually by staff; FREE plans cost nothing, are self-serve, and never renew (price 0 + LIFETIME period).', max_length=10),
        ),
        migrations.AlterField(
            model_name='membershipsubscriptionplan',
            name='period_unit',
            field=models.CharField(choices=[('month', 'Month'), ('year', 'Year'), ('lifetime', 'Lifetime')], default='month', max_length=10),
        ),
    ]
