# Generated by Django 5.2.16 on 2026-08-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0110_alter_historicalmembershipsubscriptionplan_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='require_ticket_names',
            field=models.BooleanField(default=True, help_text='Require a holder name for every ticket at checkout. When off, names are optional and checkout is faster.'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='guest_name',
            field=models.CharField(blank=True, help_text='Name of the ticket holder (may differ from purchasing user).', max_length=255),
        ),
    ]
