# Generated by Django 5.2.17 on 2026-08-09 22:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0111_event_require_ticket_names_alter_ticket_guest_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='tickets_refund_started_at',
            field=models.DateTimeField(blank=True, editable=False, help_text='Stamped when the bulk cancel-and-refund sweep was dispatched. Non-null blocks un-cancelling the event. Staff-only — never expose in public schemas.', null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='cancellation_source',
            field=models.CharField(blank=True, choices=[('user', 'User self-service'), ('organizer', 'Organizer via admin'), ('stripe_dashboard', 'Stripe dashboard'), ('event_cancellation', 'Bulk event cancellation')], db_index=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('succeeded_at', models.DateTimeField(blank=True, editable=False, help_text='When the charge.refunded webhook confirmed this refund as SUCCEEDED. Revenue reporting attributes the refund to the period containing this date.', null=True)),
                ('stripe_refund_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('failure_reason', models.TextField(blank=True, default='')),
                ('reason', models.CharField(blank=True, default='', max_length=500)),
                ('source', models.CharField(choices=[('organizer_api', 'Organizer via API'), ('user_cancellation', 'User self-service cancellation'), ('event_cancellation', 'Bulk event cancellation'), ('stripe_dashboard', 'Stripe dashboard')], db_index=True, max_length=20)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='events.payment')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddField(
            model_name='attendeeinvoicecreditnote',
            name='refunds',
            field=models.ManyToManyField(blank=True, help_text='The refund attempts this credit note covers (amount-aware partial refunds).', related_name='credit_notes', to='events.refund'),
        ),
    ]
