# Generated by Django 5.2.17 on 2026-08-10 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0113_backfill_refund_rows'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_virtual',
            field=models.BooleanField(default=False, help_text='Virtual (streamed) attendance — changes the VAT place-of-supply rules.'),
        ),
        migrations.AddField(
            model_name='event',
            name='vat_country_code',
            field=models.CharField(blank=True, default='', help_text="Explicit VAT country override (ISO 3166-1 alpha-2). Blank = derived from the venue's city, then the event's city, falling back to the organization's VAT country.", max_length=2),
        ),
    ]
