# Generated by Django 5.2.17 on 2026-08-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0114_event_place_of_supply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='max_tickets_per_user',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Maximum tickets a user can purchase for this event, across all tiers. Null = unlimited.', null=True),
        ),
        migrations.AlterField(
            model_name='tickettier',
            name='max_tickets_per_user',
            field=models.PositiveIntegerField(blank=True, help_text='Additional per-tier cap on tickets per user. Null = no per-tier cap (the event-level cap still applies).', null=True),
        ),
    ]
