# Generated by Django 5.2.17 on 2026-09-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0116_backfill_layered_ticket_caps'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='sales_paused',
            field=models.BooleanField(db_index=True, default=False, help_text='Organizer kill switch: hides the tier from checkout until resumed. Independent of the sales window.'),
        ),
    ]
