# Generated by Django 5.2.17 on 2026-09-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0117_tickettier_sales_paused'),
    ]

    operations = [
        migrations.AddField(
            model_name='heldseriespass',
            name='attribution',
            field=models.JSONField(blank=True, help_text='Campaign tags the pass was bought through (#922); copied onto every ticket materialised for it, including later backfills and series extensions.', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='attribution',
            field=models.JSONField(blank=True, help_text='Campaign tags (utm_source/medium/campaign/content) the buyer arrived with, as sent by the checkout payload (#922). Null when the URL carried none. Never updated.', null=True),
        ),
    ]
