# Generated by Django 5.2.17 on 2026-09-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0118_ticket_heldseriespass_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinvitationrequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organizationmembershiprequest',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
