# Generated by Django 5.2.17 on 2026-09-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0119_drop_userrequest_message_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='tickettier',
            name='events_tick_id_0b8cd6_idx',
        ),
    ]
