# Generated by Django 5.2.17 on 2026-09-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0120_drop_tickettier_pk_leading_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='sale_source',
            field=models.CharField(blank=True, choices=[('checkout', 'Checkout'), ('box_office_sale', 'Box office sale'), ('box_office_comp', 'Box office comp'), ('series_pass', 'Series pass')], editable=False, help_text='How the ticket was issued (#1013). Null for tickets created before this was recorded.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='offline_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, help_text='Amount refunded for a manually-collected offline/at-the-door ticket. Set when a paid ticket is cancelled — 0.00 means the organizer kept the money (#1010); null means nothing was collected (or the ticket is not cancelled). Online (Stripe) refunds are tracked on Payment.refund_amount instead.', max_digits=10, null=True),
        ),
    ]
