# Generated by Django 5.2.17 on 2026-09-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0121_ticket_sale_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickettier',
            name='check_in_closes_offset',
            field=models.DurationField(blank=True, help_text="When check-in closes for this tier, relative to the event start. Null = the event's check-in window.", null=True),
        ),
        migrations.AddField(
            model_name='tickettier',
            name='check_in_opens_offset',
            field=models.DurationField(blank=True, help_text="When check-in opens for this tier, relative to the event start (may be negative). Null = the event's check-in window.", null=True),
        ),
    ]
