# Generated by Django 5.2.17 on 2026-09-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0122_ticket_tier_check_in_offsets'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='billing_email',
            field=models.EmailField(blank=True, default='', help_text='Email address for invoice delivery and the attendee-invoice BCC copy. When empty, the invoice copy falls back to the contact email only if it is verified.', max_length=254),
        ),
    ]
