# Generated by Django 5.2.17 on 2026-10-01 09:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0123_billing_email_help_text'),
        ('notifications', '0030_org_setup_nudges'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationNudge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('trigger', models.CharField(choices=[('draft_event', 'Draft event forgotten'), ('private_profile', 'Profile still private'), ('no_events', 'No events yet'), ('check_in', 'Founder check-in'), ('dormant', 'Dormant organization')], max_length=32)),
                ('episode_key', models.CharField(blank=True, default='', max_length=64)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='notifications.notification')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nudges', to='events.organization')),
                ('target_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='events.event')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='events_orga_organiz_4129d4_idx')],
                'constraints': [models.UniqueConstraint(fields=('organization', 'trigger', 'episode_key', 'sequence'), name='unique_org_nudge_sequence'), models.CheckConstraint(condition=models.Q(('sequence__gte', 1), ('sequence__lte', 2)), name='org_nudge_sequence_1_or_2')],
            },
        ),
    ]
