# Generated by Django 5.2.17 on 2026-10-01 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0125_org_setup_nudges_beat'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketNumberSequence',
            fields=[
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ticket_number_sequence', serialize=False, to='events.organization')),
                ('series', models.CharField(max_length=16)),
                ('last_number', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='issued_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_series',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
    ]
