# Generated by Django 5.2.17 on 2026-10-02 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0128_disable_blocked_attendee_invoicing'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='attribution',
            field=models.JSONField(blank=True, help_text='Campaign tags (utm_source/medium/campaign/content) the owner arrived with, as sent by the create-organization payload (#1075). Null when the URL carried none. Never updated.', null=True),
        ),
    ]
