# Generated by Django 5.2.17 on 2026-10-02 10:40

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0129_organization_attribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkippedFiscalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('kind', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit Note')], max_length=20)),
                ('reason_code', models.CharField(choices=[('b2b_e_invoicing', 'B2B E Invoicing'), ('fiscalized_invoicing', 'Fiscalized Invoicing')], max_length=30)),
                ('policy_country', models.CharField(help_text='The country whose policy refused the document.', max_length=2)),
                ('reason', models.TextField(help_text="The policy's explanation, in the language active when it was decided.")),
                ('stripe_session_id', models.CharField(db_index=True, max_length=255)),
                ('buyer_name', models.CharField(blank=True, default='', max_length=255)),
                ('buyer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('buyer_vat_id', models.CharField(blank=True, default='', max_length=20)),
                ('buyer_vat_country', models.CharField(blank=True, default='', max_length=2)),
                ('buyer_address', models.TextField(blank=True, default='')),
                ('buyer_vat_id_status', models.CharField(blank=True, default='', max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('total_gross', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_vat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_items', models.JSONField(blank=True, default=list)),
                ('decided_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('external_reference', models.CharField(blank=True, default='', help_text="The document number in the organizer's own system.", max_length=255)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_fiscal_documents', to='events.event')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_credit_notes', to='events.attendeeinvoice')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_fiscal_documents', to='events.organization')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_credit_notes', to='events.skippedfiscaldocument')),
                ('payments', models.ManyToManyField(blank=True, related_name='skipped_fiscal_documents', to='events.payment')),
                ('refunds', models.ManyToManyField(blank=True, related_name='skipped_fiscal_documents', to='events.refund')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_fiscal_documents', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skipped_fiscal_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-decided_at'],
                'indexes': [models.Index(fields=['organization', 'decided_at'], name='events_skip_organiz_d4947b_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'invoice')), fields=('stripe_session_id',), name='unique_skipped_invoice_per_session')],
            },
        ),
    ]
