# Generated by Django 5.2.3 on 2025-11-05 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='erroroccurrence',
            name='signature',
        ),
        migrations.DeleteModel(
            name='Error',
        ),
        migrations.DeleteModel(
            name='ErrorOccurrence',
        ),
    ]
