# Generated by Django 5.2.8 on 2025-11-29 22:44

import django.db.models.deletion
import uuid
import wallet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0019_drop_unique_organization_name_constraint'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletPassDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('device_library_id', models.CharField(db_index=True, help_text='Unique identifier provided by the wallet app for this device.', max_length=255, unique=True)),
                ('push_token', models.CharField(help_text='Token used to send push notifications to this device.', max_length=255)),
                ('platform', models.CharField(choices=[('apple', 'Apple Wallet'), ('google', 'Google Wallet')], db_index=True, default='apple', max_length=10)),
            ],
            options={
                'verbose_name': 'Wallet Pass Device',
                'verbose_name_plural': 'Wallet Pass Devices',
            },
        ),
        migrations.CreateModel(
            name='WalletPassRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('auth_token', models.CharField(db_index=True, default=wallet.models.generate_auth_token, help_text='Authentication token for validating pass update requests.', max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='wallet.walletpassdevice')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallet_registrations', to='events.ticket')),
            ],
            options={
                'verbose_name': 'Wallet Pass Registration',
                'verbose_name_plural': 'Wallet Pass Registrations',
                'indexes': [models.Index(fields=['ticket', 'device'], name='wallet_wall_ticket__bceb55_idx'), models.Index(fields=['auth_token'], name='wallet_wall_auth_to_a7116d_idx')],
                'constraints': [models.UniqueConstraint(fields=('ticket', 'device'), name='unique_ticket_device_registration')],
            },
        ),
        migrations.CreateModel(
            name='WalletPassUpdateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('update_type', models.CharField(choices=[('generated', 'Pass Generated'), ('push_sent', 'Push Notification Sent'), ('push_failed', 'Push Notification Failed'), ('fetched', 'Pass Fetched by Device'), ('registered', 'Device Registered'), ('unregistered', 'Device Unregistered')], db_index=True, max_length=20)),
                ('details', models.JSONField(blank=True, default=dict, help_text='Additional details about the update event.')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_logs', to='wallet.walletpassdevice')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wallet_update_logs', to='events.ticket')),
            ],
            options={
                'verbose_name': 'Wallet Pass Update Log',
                'verbose_name_plural': 'Wallet Pass Update Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['ticket', '-created_at'], name='wallet_wall_ticket__218dd0_idx'), models.Index(fields=['update_type', '-created_at'], name='wallet_wall_update__d3619d_idx')],
            },
        ),
    ]
