# Generated by Django 5.2.17 on 2026-09-17 17:25

import common.fields
import django.core.validators
import django.db.models.deletion
import oauth2_provider.generators
import oauth2_provider.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    # Documented exception to "never hand-edit schema migrations" (spec §6.4): DOT's
    # 0001_initial has no dependency on the swapped Application model. Re-add after any
    # regeneration (make nuke-db / make restart). Guarded by oauth/tests/test_migrations.py.
    run_before = [("oauth2_provider", "0001_initial")]

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthApplication',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('client_id', models.CharField(db_index=True, default=oauth2_provider.generators.generate_client_id, max_length=255, unique=True, verbose_name='client ID')),
                ('redirect_uris', models.TextField(blank=True, help_text='Allowed URIs list, space separated', verbose_name='redirect URIs')),
                ('post_logout_redirect_uris', models.TextField(blank=True, default='', help_text='Allowed Post Logout URIs list, space separated', verbose_name='post logout redirect URIs')),
                ('client_type', models.CharField(choices=[('confidential', 'Confidential'), ('public', 'Public')], max_length=32, verbose_name='client type')),
                ('client_secret', oauth2_provider.models.ClientSecretField(blank=True, db_index=True, default=oauth2_provider.generators.generate_client_secret, help_text='Client secret for authentication', max_length=255, verbose_name='client secret')),
                ('hash_client_secret', models.BooleanField(default=True, verbose_name='hash client secret')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='name')),
                ('skip_authorization', models.BooleanField(default=False, verbose_name='skip authorization')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('allowed_origins', models.TextField(blank=True, default='', help_text='Allowed origins list to enable CORS, space separated', verbose_name='allowed origins')),
                ('registration_source', models.CharField(choices=[('manual', 'Manual'), ('dcr', 'Dynamic Client Registration'), ('cimd', 'Client ID Metadata Document')], default='manual', help_text='How this application was registered (manual, DCR per RFC 7591, or CIMD)', max_length=32, verbose_name='registration source')),
                ('cimd_expires_at', models.DateTimeField(blank=True, default=None, help_text='When the cached Client ID Metadata Document should be re-fetched', null=True, verbose_name='CIMD expires at')),
                ('algorithm', models.CharField(choices=[('', 'No OIDC support'), ('RS256', 'RSA with SHA-2 256'), ('HS256', 'HMAC with SHA-2 256')], default='RS256', max_length=5)),
                ('authorization_grant_type', models.CharField(choices=[('authorization-code', 'Authorization code'), ('urn:ietf:params:oauth:grant-type:device_code', 'Device Code'), ('implicit', 'Implicit'), ('password', 'Resource owner password-based'), ('client-credentials', 'Client credentials'), ('openid-hybrid', 'OpenID connect hybrid')], default='authorization-code', max_length=44)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='oauth-logos', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'webp', 'heic', 'heif']), common.fields.validate_image_file])),
                ('logo_thumbnail', models.ImageField(blank=True, help_text='150x150 logo thumbnail (auto-generated).', max_length=255, null=True, upload_to='')),
                ('homepage_url', models.URLField(blank=True)),
                ('privacy_policy_url', models.URLField(blank=True)),
                ('allowed_scopes', models.JSONField(blank=True, default=list)),
                ('verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'abstract': False,
                'swappable': 'OAUTH2_PROVIDER_APPLICATION_MODEL',
            },
        ),
    ]
