# Generated by Django 5.2.3 on 2025-08-10 20:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ascii_name', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3)),
                ('admin_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capital', models.CharField(blank=True, max_length=32, null=True)),
                ('population', models.BigIntegerField(blank=True, null=True)),
                ('city_id', models.BigIntegerField(unique=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
            ],
            options={
                'verbose_name_plural': 'cities',
                'ordering': ['-population'],
                'indexes': [models.Index(fields=['ascii_name'], name='geo_city_ascii_name'), models.Index(fields=['iso2'], name='geo_city_iso2'), models.Index(fields=['ascii_name', 'iso2'], name='geo_city_ascii_name_iso2'), models.Index(fields=['population'], name='geo_city_population'), models.Index(fields=['location'], name='geo_city_location')],
                'constraints': [models.UniqueConstraint(fields=('ascii_name', 'iso2', 'location'), name='geo_city_unique_city_location_per_country')],
            },
        ),
    ]
