# Generated by Django 5.2.10 on 2026-01-23 15:29

from django.db import migrations, models


def populate_city_timezones(apps, schema_editor):
    """Populate timezone for all existing cities using tzfpy."""
    from tzfpy import get_tz

    City = apps.get_model("geo", "City")
    cities = City.objects.filter(timezone__isnull=True)

    for city in cities.iterator():
        if city.location:
            # get_tz expects (longitude, latitude)
            city.timezone = get_tz(city.location.x, city.location.y)
            city.save(update_fields=["timezone"])


def reverse_populate(apps, schema_editor):
    """Reverse migration - clear timezone fields."""
    City = apps.get_model("geo", "City")
    City.objects.update(timezone=None)


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_add_download_ip2location_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='timezone',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.RunPython(populate_city_timezones, reverse_populate),
    ]
