# Generated by Django 5.2.15 on 2026-06-18 14:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('object_id', models.UUIDField()),
                ('content_snapshot', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('user_report', 'User report'), ('blocklist', 'Blocklist'), ('classifier', 'Classifier')], default='user_report', max_length=20)),
                ('reason', models.CharField(choices=[('offensive', 'Offensive / hateful'), ('spam', 'Spam'), ('sexual', 'Sexual content'), ('harassment', 'Harassment'), ('other', 'Other')], max_length=20)),
                ('details', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('actioned', 'Actioned'), ('dismissed', 'Dismissed')], db_index=True, default='open', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_reports', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_content_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='moderation__content_a4d034_idx'), models.Index(fields=['status', '-created_at'], name='moderation__status_4b6062_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('content_type', 'object_id', 'reporter'), name='unique_open_report_per_reporter_per_object')],
            },
        ),
    ]
