# Generated by Django 5.2.3 on 2025-11-12 21:39

import django.db.models.deletion
import telegram.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='blocked_by_user',
            field=models.BooleanField(default=False, help_text='True if the user has blocked the bot.'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Linked Revel user account (null until account linking is complete)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telegram_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_is_deactivated',
            field=models.BooleanField(default=False, help_text='True if the user has deactivated their account.'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='was_welcomed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AccountOTP',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(default=telegram.models.generate_otp, max_length=9, unique=True)),
                ('used_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True, default=telegram.models.get_otp_expiration_time)),
                ('tg_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_otp', to='telegram.telegramuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
