# Generated by Django 5.2.3 on 2025-11-18 11:03

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallegal',
            name='privacy_policy',
            field=common.fields.MarkdownField(blank=True, default='', help_text='Privacy Policy text in markdown format'),
        ),
        migrations.AlterField(
            model_name='historicallegal',
            name='terms_and_conditions',
            field=common.fields.MarkdownField(blank=True, default='', help_text='Terms and Conditions text in markdown format'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='privacy_policy',
            field=common.fields.MarkdownField(blank=True, default='', help_text='Privacy Policy text in markdown format'),
        ),
        migrations.AlterField(
            model_name='legal',
            name='terms_and_conditions',
            field=common.fields.MarkdownField(blank=True, default='', help_text='Terms and Conditions text in markdown format'),
        ),
    ]
