# Generated by Django 5.2.11 on 2026-02-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_historicallegal_privacy_policy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='maintenance_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the maintenance window ends. Banner is hidden after this time.', null=True),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='maintenance_message',
            field=models.CharField(blank=True, default='', help_text='Message to display in the maintenance banner. Leave blank to disable.', max_length=500),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='maintenance_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When the maintenance window starts.', null=True),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='maintenance_severity',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', help_text='Severity level of the maintenance banner.', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_ends_at',
            field=models.DateTimeField(blank=True, help_text='When the maintenance window ends. Banner is hidden after this time.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_message',
            field=models.CharField(blank=True, default='', help_text='Message to display in the maintenance banner. Leave blank to disable.', max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_scheduled_at',
            field=models.DateTimeField(blank=True, help_text='When the maintenance window starts.', null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='maintenance_severity',
            field=models.CharField(choices=[('debug', 'Debug'), ('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', help_text='Severity level of the maintenance banner.', max_length=20),
        ),
    ]
