# Generated by Django

from django.db import migrations


def create_file_export_cleanup_task(apps, schema_editor):
    """Create periodic task to cleanup expired file export files."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Run every hour at minute 30
    hourly_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="30",
        hour="*",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Cleanup expired file exports",
        defaults={
            "task": "common.tasks.cleanup_expired_file_exports",
            "crontab": hourly_schedule,
            "enabled": True,
        },
    )


def delete_file_export_cleanup_task(apps, schema_editor):
    """Remove periodic task for file export cleanup."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Cleanup expired file exports")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0004_fileexport"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_file_export_cleanup_task,
            reverse_code=delete_file_export_cleanup_task,
        ),
    ]
