# Generated by Django 5.2.11 on 2026-03-10 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_file_export_cleanup_periodic_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='platform_business_address',
            field=models.TextField(blank=True, default='', help_text='Full business address for invoices.'),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='platform_business_name',
            field=models.CharField(blank=True, default='', help_text="Legal business name for invoices (e.g., 'Revel S.r.l.').", max_length=255),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='platform_invoice_bcc_email',
            field=models.EmailField(blank=True, default='', help_text='BCC email for all platform fee invoices (internal accounting copy).', max_length=254),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='platform_vat_country',
            field=models.CharField(blank=True, default='', help_text="ISO 3166-1 alpha-2 country code for platform's VAT registration.", max_length=2),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='platform_vat_id',
            field=models.CharField(blank=True, default='', help_text="Platform's VAT ID including country prefix (e.g., IT12345678901).", max_length=20),
        ),
        migrations.AddField(
            model_name='historicalsitesettings',
            name='platform_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Platform's domestic VAT rate (e.g., 22.00 for 22%).", max_digits=5),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_business_address',
            field=models.TextField(blank=True, default='', help_text='Full business address for invoices.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_business_name',
            field=models.CharField(blank=True, default='', help_text="Legal business name for invoices (e.g., 'Revel S.r.l.').", max_length=255),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_invoice_bcc_email',
            field=models.EmailField(blank=True, default='', help_text='BCC email for all platform fee invoices (internal accounting copy).', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_vat_country',
            field=models.CharField(blank=True, default='', help_text="ISO 3166-1 alpha-2 country code for platform's VAT registration.", max_length=2),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_vat_id',
            field=models.CharField(blank=True, default='', help_text="Platform's VAT ID including country prefix (e.g., IT12345678901).", max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='platform_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Platform's domestic VAT rate (e.g., 22.00 for 22%).", max_digits=5),
        ),
    ]
