# Generated by Django 5.2.11 on 2026-03-11 08:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_historicalsitesettings_platform_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsitesettings',
            name='platform_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Platform's domestic VAT rate (e.g., 22.00 for 22%).", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='platform_vat_rate',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Platform's domestic VAT rate (e.g., 22.00 for 22%).", max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
