# Generated by Django 5.2.11 on 2026-03-22 09:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0007_alter_historicalsitesettings_platform_vat_rate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('base', models.CharField(default='EUR', max_length=3)),
                ('date', models.DateField(db_index=True)),
                ('rates', models.JSONField(help_text='Mapping of currency code → rate relative to base')),
            ],
            options={
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('base', 'date'), name='unique_exchange_rate_per_day')],
            },
        ),
    ]
