# Generated by Django

from django.db import migrations


def create_exchange_rate_task(apps, schema_editor):
    """Create periodic task to fetch daily exchange rates."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Run daily at 04:00 UTC
    daily_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="0",
        hour="4",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name="Fetch daily exchange rates",
        defaults={
            "task": "common.fetch_exchange_rates",
            "crontab": daily_schedule,
            "enabled": True,
        },
    )


def delete_exchange_rate_task(apps, schema_editor):
    """Remove periodic task for exchange rate fetching."""
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    try:
        task = PeriodicTask.objects.get(name="Fetch daily exchange rates")
        task.delete()
    except PeriodicTask.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0008_exchangerate"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_exchange_rate_task,
            reverse_code=delete_exchange_rate_task,
        ),
    ]
