# Generated by Django

import datetime

from django.db import migrations

# ECB rates via frankfurter.app, fetched 2026-03-22
SEED_DATE = datetime.date(2026, 3, 20)
SEED_RATES = {
    "AUD": 1.6351,
    "BRL": 6.0724,
    "CAD": 1.5849,
    "CHF": 0.9096,
    "CNY": 7.9664,
    "CZK": 24.505,
    "DKK": 7.4712,
    "GBP": 0.86438,
    "HKD": 9.0545,
    "HUF": 392.48,
    "IDR": 19557,
    "ILS": 3.5888,
    "INR": 108.18,
    "ISK": 143.8,
    "JPY": 183.46,
    "KRW": 1734.17,
    "MXN": 20.588,
    "MYR": 4.5521,
    "NOK": 11.029,
    "NZD": 1.9723,
    "PHP": 69.18,
    "PLN": 4.2783,
    "RON": 5.096,
    "SEK": 10.7825,
    "SGD": 1.4793,
    "THB": 37.854,
    "TRY": 51.197,
    "USD": 1.1555,
    "ZAR": 19.5117,
}


def seed_exchange_rates(apps, schema_editor):
    """Seed initial exchange rates so currency conversion works before the daily task runs."""
    ExchangeRate = apps.get_model("common", "ExchangeRate")
    if not ExchangeRate.objects.exists():
        ExchangeRate.objects.create(base="EUR", date=SEED_DATE, rates=SEED_RATES)


def reverse_seed(apps, schema_editor):
    ExchangeRate = apps.get_model("common", "ExchangeRate")
    ExchangeRate.objects.filter(base="EUR", date=SEED_DATE).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_add_exchange_rate_periodic_task"),
    ]

    operations = [
        migrations.RunPython(
            seed_exchange_rates,
            reverse_code=reverse_seed,
        ),
    ]
