# Generated by Django

import structlog
from django.db import migrations

logger = structlog.get_logger(__name__)

FRANKFURTER_URL = "https://api.frankfurter.app/latest"


def seed_exchange_rates(apps, schema_editor):
    """Fetch initial exchange rates from frankfurter.app.

    This ensures exchange rates are available immediately after deployment,
    before the daily Celery task has had a chance to run. Without this,
    checkout and payout calculations that involve currency conversion would
    fail with ExchangeRate.DoesNotExist.
    """
    import datetime

    import httpx

    ExchangeRate = apps.get_model("common", "ExchangeRate")

    # Skip if rates already exist (e.g., re-running migrations)
    if ExchangeRate.objects.exists():
        return

    try:
        response = httpx.get(FRANKFURTER_URL, params={"base": "EUR"}, timeout=15)
        response.raise_for_status()
        data = response.json()

        ExchangeRate.objects.create(
            base="EUR",
            date=datetime.date.fromisoformat(data["date"]),
            rates=data["rates"],
        )
        logger.info("exchange_rates_seeded", date=data["date"], currencies=len(data["rates"]))
    except Exception as e:
        # Non-fatal: the daily task will pick it up. Log and continue.
        logger.warning("exchange_rates_seed_failed", error=str(e))


def reverse_seed(apps, schema_editor):
    """Remove seeded exchange rates."""
    ExchangeRate = apps.get_model("common", "ExchangeRate")
    ExchangeRate.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0009_add_exchange_rate_periodic_task"),
    ]

    operations = [
        migrations.RunPython(
            seed_exchange_rates,
            reverse_code=reverse_seed,
        ),
    ]
