# Generated by Django 5.2.11 on 2026-04-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0010_seed_exchange_rates'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='notify_organization_created',
            field=models.BooleanField(default=False, help_text='Send a notification when a new organization is created.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='notify_organization_created',
            field=models.BooleanField(default=False, help_text='Send a notification when a new organization is created.'),
        ),
    ]
