# Generated by Django

from django.db import migrations


_CLEANUP_TASK_NAME = "Cleanup email logs"
_CLEANUP_TASK_PATH = "common.tasks.cleanup_email_logs"


def create_cleanup_email_logs_task(apps, schema_editor):
    """Register the daily ``cleanup_email_logs`` beat task."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    # Daily at 04:30 UTC. Sits between ``expire_subscriptions_past_grace``
    # (04:00) and ``send_subscription_renewal_reminders`` (05:00).
    daily_schedule, _ = CrontabSchedule.objects.get_or_create(
        minute="30",
        hour="4",
        day_of_week="*",
        day_of_month="*",
        month_of_year="*",
        timezone="UTC",
    )

    PeriodicTask.objects.update_or_create(
        name=_CLEANUP_TASK_NAME,
        defaults={
            "task": _CLEANUP_TASK_PATH,
            "crontab": daily_schedule,
            "enabled": True,
        },
    )


def delete_cleanup_email_logs_task(apps, schema_editor):
    """Remove the cleanup-email-logs beat task and its schedule if unused."""
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")
    PeriodicTask = apps.get_model("django_celery_beat", "PeriodicTask")

    schedule_ids = list(
        PeriodicTask.objects.filter(name=_CLEANUP_TASK_NAME)
        .exclude(crontab__isnull=True)
        .values_list("crontab_id", flat=True)
    )
    PeriodicTask.objects.filter(name=_CLEANUP_TASK_NAME).delete()

    for schedule_id in schedule_ids:
        if not PeriodicTask.objects.filter(crontab_id=schedule_id).exists():
            CrontabSchedule.objects.filter(pk=schedule_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0011_historicalsitesettings_notify_organization_created_and_more"),
        ("django_celery_beat", "0019_alter_periodictasks_options"),
    ]

    operations = [
        migrations.RunPython(
            create_cleanup_email_logs_task,
            reverse_code=delete_cleanup_email_logs_task,
        ),
    ]
