# Generated by Django 5.2.14 on 2026-05-27 11:21

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_add_cleanup_email_logs_periodic_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quarantinedfile',
            name='file',
            field=common.fields.ProtectedFileField(upload_to='protected/quarantined_files'),
        ),
    ]
