# Generated by Django 5.2.15 on 2026-06-19 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0014_relocate_quarantined_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileexport",
            name="export_type",
            field=models.CharField(
                choices=[
                    ("questionnaire_submissions", "Questionnaire Submissions"),
                    ("attendee_list", "Attendee List"),
                    ("revenue_vat_report", "Revenue Vat Report"),
                ],
                db_index=True,
                max_length=40,
            ),
        ),
    ]
