# Generated by Django 5.2.17 on 2026-09-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_alter_fileexport_export_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsitesettings',
            name='demo_booking_url',
            field=models.URLField(blank=True, default='', help_text='Public link to book a product demo (e.g. a Cal.com/Calendly page). Leave blank to hide.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='demo_booking_url',
            field=models.URLField(blank=True, default='', help_text='Public link to book a product demo (e.g. a Cal.com/Calendly page). Leave blank to hide.'),
        ),
    ]
