# Generated by Django 5.2.17 on 2026-09-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0016_sitesettings_demo_booking_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsitesettings",
            name="referral_applications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Accept public applications to the referral program. Admin invites work regardless.",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="referral_applications_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Accept public applications to the referral program. Admin invites work regardless.",
            ),
        ),
    ]
